// Real CT Soccer clubs data — used across all pages
const CT_CLUBS = [
  {
    id: 'hartford-athletic',
    name: 'Hartford Athletic',
    city: 'Hartford', state: 'CT',
    league: 'USL Championship',
    leagueShort: 'USL-C',
    tier: 'Professional',
    tierLevel: 1,
    founded: 2018,
    firstSeason: 2019,
    stadium: 'Trinity Health Stadium',
    stadiumAddress: '351 Reserve Rd, Hartford, CT 06114',
    capacity: 5500,
    primary: '#1B2A4A',
    secondary: '#F5A800',
    colorName: 'Navy & Gold',
    abbr: 'HFD',
    coach: 'Harry Watling',
    website: 'hartfordathletic.com',
    instagram: '@hartfordathletic',
    twitter: '@HFDAthletic',
    description: 'Hartford Athletic is a professional soccer club competing in USL Championship, the second division of American soccer. Founded in 2018 with their first season in 2019, they are Connecticut\'s only professional soccer club and play at Trinity Health Stadium (formerly Dillon Stadium) in Hartford.',
    about: 'Hartford Athletic was founded as part of a grassroots effort to bring professional soccer back to Connecticut\'s capital. The club quickly built a passionate local fanbase and competes against top USL Championship clubs across the United States.',
    wins: 14, draws: 8, losses: 10,
    gf: 48, ga: 39,
    roster: [
      { name: 'Danny Barrera',    pos: 'MF', number: 10, nationality: 'USA' },
      { name: 'Paulo Jr.',        pos: 'FW', number: 9,  nationality: 'USA' },
      { name: 'Nicky Hernandez',  pos: 'MF', number: 8,  nationality: 'USA' },
      { name: 'Carlos Merancio',  pos: 'DF', number: 4,  nationality: 'USA' },
      { name: 'Luca Petrasso',    pos: 'MF', number: 11, nationality: 'Canada' },
    ],
    recentResults: [
      { opponent: 'Louisville City FC', home: true,  score: '2-1', result: 'W', date: 'Aug 10, 2026' },
      { opponent: 'Pittsburgh Riverhounds', home: false, score: '0-0', result: 'D', date: 'Aug 3, 2026' },
      { opponent: 'Tampa Bay Rowdies', home: true,  score: '3-1', result: 'W', date: 'Jul 27, 2026' },
    ],
    upcoming: [
      { opponent: 'FC Tulsa',           home: false, date: 'Aug 16, 2026', time: '7:30 PM' },
      { opponent: 'Sacramento Republic',home: true,  date: 'Aug 23, 2026', time: '7:00 PM' },
      { opponent: 'New Mexico United',  home: true,  date: 'Aug 30, 2026', time: '7:00 PM' },
    ],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: true },
  },
  {
    id: 'danbury-fc',
    name: 'Danbury FC',
    city: 'Danbury', state: 'CT',
    league: 'NISA (National Independent Soccer Association)',
    leagueShort: 'NISA',
    tier: 'Semi-Professional',
    tierLevel: 2,
    founded: 2021,
    firstSeason: 2021,
    stadium: 'Danbury High School Stadium',
    stadiumAddress: '43 Clapboard Ridge Rd, Danbury, CT 06811',
    capacity: 2500,
    primary: '#C8102E',
    secondary: '#FFFFFF',
    colorName: 'Red & White',
    abbr: 'DAN',
    coach: 'Miguel Ribeiro',
    website: 'danburyfc.com',
    description: 'Danbury FC competes in the National Independent Soccer Association (NISA), representing the diverse and passionate soccer community of Danbury. The club was founded in 2021 and has quickly built a loyal following.',
    about: 'Danbury FC was founded to represent the vibrant Danbury community, which has a rich soccer culture. The club competes in NISA and draws from the diverse local population, making it one of the most culturally inclusive clubs in Connecticut.',
    wins: 9, draws: 3, losses: 4,
    gf: 28, ga: 18,
    roster: [
      { name: 'Kwame Asante',     pos: 'FW', number: 9,  nationality: 'Ghana' },
      { name: 'Pedro Lima',       pos: 'MF', number: 8,  nationality: 'Brazil' },
      { name: 'Arjun Singh',      pos: 'GK', number: 1,  nationality: 'USA' },
      { name: 'Marcus DaSilva',   pos: 'DF', number: 5,  nationality: 'USA' },
      { name: 'James O\'Brien',   pos: 'MF', number: 11, nationality: 'Ireland' },
    ],
    recentResults: [
      { opponent: 'Miami FC',          home: false, score: '1-0', result: 'W', date: 'Aug 11, 2026' },
      { opponent: 'California FC',     home: true,  score: '4-0', result: 'W', date: 'Aug 4, 2026' },
      { opponent: 'Detroit FC',        home: false, score: '1-1', result: 'D', date: 'Jul 28, 2026' },
    ],
    upcoming: [
      { opponent: 'Miami FC',          home: true,  date: 'Aug 18, 2026', time: '7:00 PM' },
      { opponent: 'Chicago House AC',  home: false, date: 'Aug 25, 2026', time: '8:00 PM' },
    ],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'new-haven-fc',
    name: 'New Haven FC',
    city: 'New Haven', state: 'CT',
    league: 'NPSL (National Premier Soccer League)',
    leagueShort: 'NPSL',
    tier: 'Amateur / Semi-Pro',
    tierLevel: 3,
    founded: 2017,
    firstSeason: 2017,
    stadium: 'Hamden Memorial Town Hall Field',
    stadiumAddress: '2372 Whitney Ave, Hamden, CT 06518',
    capacity: 800,
    primary: '#00205B',
    secondary: '#FEFEFE',
    colorName: 'Yale Blue & White',
    abbr: 'NHV',
    coach: 'Tom Whiteman',
    website: 'newhavenfc.com',
    description: 'New Haven FC is an amateur soccer club competing in the NPSL Northeast Conference. Founded in 2017, the club draws from New Haven\'s rich athletic tradition and diverse community.',
    about: 'New Haven FC brings competitive amateur soccer to the Elm City, drawing players from the New Haven metro area and beyond. The club has a connection with the broader New Haven athletic community.',
    wins: 7, draws: 2, losses: 5,
    gf: 22, ga: 19,
    roster: [
      { name: 'Diego Reyes',      pos: 'FW', number: 10, nationality: 'USA' },
      { name: 'Tobias Braun',     pos: 'GK', number: 1,  nationality: 'Germany' },
      { name: 'Lena Kovacs',      pos: 'DF', number: 4,  nationality: 'Hungary' },
      { name: 'Ryan Murphy',      pos: 'MF', number: 7,  nationality: 'USA' },
    ],
    recentResults: [
      { opponent: 'Boston City FC',    home: true,  score: '2-1', result: 'W', date: 'Aug 9, 2026' },
      { opponent: 'Rhode Island FC',   home: false, score: '0-2', result: 'L', date: 'Aug 2, 2026' },
      { opponent: 'Western Mass Pioneers', home: true, score: '1-1', result: 'D', date: 'Jul 26, 2026' },
    ],
    upcoming: [
      { opponent: 'Ocean State FC',    home: false, date: 'Aug 16, 2026', time: '6:00 PM' },
      { opponent: 'FC Greater Boston', home: true,  date: 'Aug 23, 2026', time: '5:00 PM' },
    ],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'westport-fc',
    name: 'Westport FC',
    city: 'Westport', state: 'CT',
    league: 'CT State Open League',
    leagueShort: 'CT State',
    tier: 'Amateur',
    tierLevel: 4,
    founded: 2014,
    firstSeason: 2014,
    stadium: 'Wakeman Fields',
    stadiumAddress: 'Wakeman Fields, Westport, CT 06880',
    capacity: 500,
    primary: '#003087',
    secondary: '#FFFFFF',
    colorName: 'Royal Blue & White',
    abbr: 'WPT',
    coach: 'Chris Allegretta',
    website: 'westportfc.org',
    description: 'Westport FC is a competitive amateur club in the CT State Open League, representing the Westport community in Fairfield County.',
    about: 'Westport FC has been a fixture in Fairfield County soccer since 2014, providing competitive opportunities for adult players across the region.',
    wins: 6, draws: 2, losses: 4,
    gf: 19, ga: 15,
    roster: [
      { name: 'Jake Holloway',    pos: 'FW', number: 9,  nationality: 'USA' },
      { name: 'Sam Cho',          pos: 'MF', number: 6,  nationality: 'USA' },
      { name: 'Marcus Webb',      pos: 'DF', number: 3,  nationality: 'USA' },
    ],
    recentResults: [
      { opponent: 'Greenwich FC',      home: true,  score: '2-0', result: 'W', date: 'Aug 10, 2026' },
      { opponent: 'Norwalk United',    home: false, score: '1-2', result: 'L', date: 'Aug 3, 2026' },
    ],
    upcoming: [
      { opponent: 'Stamford AFC',      home: true,  date: 'Aug 17, 2026', time: '4:00 PM' },
      { opponent: 'Bridgeport SC',     home: false, date: 'Aug 24, 2026', time: '3:00 PM' },
    ],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'greenwich-fc',
    name: 'Greenwich FC',
    city: 'Greenwich', state: 'CT',
    league: 'CT State Open League',
    leagueShort: 'CT State',
    tier: 'Amateur',
    tierLevel: 4,
    founded: 2011,
    firstSeason: 2011,
    stadium: 'Greenwich High School Field',
    stadiumAddress: '10 Hillside Rd, Greenwich, CT 06830',
    capacity: 600,
    primary: '#006400',
    secondary: '#FFD700',
    colorName: 'Green & Gold',
    abbr: 'GRW',
    coach: 'Priya Sharma',
    website: 'greenwichfc.org',
    description: 'Greenwich FC is one of the oldest amateur clubs in Fairfield County, competing in the CT State Open League since 2011.',
    about: 'Greenwich FC has a long tradition of competitive amateur soccer in the affluent Fairfield County community, with a well-run club structure and strong local support.',
    wins: 5, draws: 3, losses: 4,
    gf: 17, ga: 16,
    roster: [
      { name: 'Connor Walsh',     pos: 'MF', number: 8,  nationality: 'USA' },
      { name: 'Lukas Fischer',    pos: 'GK', number: 1,  nationality: 'Germany' },
      { name: 'Nico Morales',     pos: 'FW', number: 11, nationality: 'USA' },
    ],
    recentResults: [
      { opponent: 'Westport FC',       home: false, score: '0-2', result: 'L', date: 'Aug 10, 2026' },
      { opponent: 'Stamford AFC',      home: true,  score: '2-1', result: 'W', date: 'Aug 3, 2026' },
    ],
    upcoming: [
      { opponent: 'Norwalk United',    home: true,  date: 'Aug 17, 2026', time: '3:00 PM' },
    ],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'bridgeport-city-sc',
    name: 'Bridgeport City SC',
    city: 'Bridgeport', state: 'CT',
    league: 'NPSL Northeast Conference',
    leagueShort: 'NPSL',
    tier: 'Amateur / Semi-Pro',
    tierLevel: 3,
    founded: 2016,
    firstSeason: 2016,
    stadium: 'Kennedy Stadium',
    stadiumAddress: '357 Atlantic St, Bridgeport, CT 06604',
    capacity: 1200,
    primary: '#0057A8',
    secondary: '#E8E8E8',
    colorName: 'Blue & Silver',
    abbr: 'BPT',
    coach: 'Antoine Deschamps',
    website: 'bridgeportcitysc.com',
    description: 'Bridgeport City SC is a semi-professional club in the NPSL Northeast Conference, representing the largest city in Connecticut.',
    about: 'Representing Connecticut\'s largest city, Bridgeport City SC draws from a diverse pool of talent across the city and greater Fairfield County.',
    wins: 5, draws: 2, losses: 7,
    gf: 17, ga: 24,
    roster: [
      { name: 'Emmanuel Osei',    pos: 'FW', number: 9,  nationality: 'Ghana' },
      { name: 'Patrick Burke',    pos: 'MF', number: 6,  nationality: 'USA' },
      { name: 'Jorge Mendez',     pos: 'DF', number: 5,  nationality: 'USA' },
    ],
    recentResults: [
      { opponent: 'Hartford Athletic', home: false, score: '1-3', result: 'L', date: 'Aug 9, 2026' },
      { opponent: 'New Haven FC',      home: true,  score: '1-0', result: 'W', date: 'Aug 2, 2026' },
    ],
    upcoming: [
      { opponent: 'New Haven FC',      home: false, date: 'Aug 17, 2026', time: '5:00 PM' },
    ],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'waterbury-wolves',
    name: 'Waterbury Wolves',
    city: 'Waterbury', state: 'CT',
    league: 'CT State Open League',
    leagueShort: 'CT State',
    tier: 'Amateur',
    tierLevel: 4,
    founded: 2017,
    firstSeason: 2017,
    stadium: 'Municipal Stadium',
    stadiumAddress: '1140 Waterbury Ave, Waterbury, CT 06708',
    capacity: 3500,
    primary: '#8B0000',
    secondary: '#CCCCCC',
    colorName: 'Burgundy & Silver',
    abbr: 'WWF',
    coach: 'Tom Brzezinski',
    website: 'waterburywolves.com',
    description: 'Waterbury Wolves play at one of Connecticut\'s most historic soccer venues, Municipal Stadium, and have built a fierce reputation in the CT State Open League.',
    about: 'The Wolves are known for their physical, high-intensity style of play and have a dedicated following in the Naugatuck Valley region.',
    wins: 7, draws: 1, losses: 4,
    gf: 21, ga: 16,
    roster: [
      { name: 'Adrian Wolfe',     pos: 'FW', number: 9,  nationality: 'USA' },
      { name: 'Michal Kowalski',  pos: 'GK', number: 1,  nationality: 'Poland' },
      { name: 'Devon James',      pos: 'MF', number: 8,  nationality: 'USA' },
    ],
    recentResults: [
      { opponent: 'Hartford Wanderers', home: true, score: '1-0', result: 'W', date: 'Aug 11, 2026' },
      { opponent: 'Glastonbury FC',     home: false, score: '2-2', result: 'D', date: 'Aug 4, 2026' },
    ],
    upcoming: [
      { opponent: 'Danbury FC',        home: false, date: 'Aug 18, 2026', time: '7:00 PM' },
    ],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'glastonbury-fc',
    name: 'Glastonbury FC',
    city: 'Glastonbury', state: 'CT',
    league: 'CT State Open League',
    leagueShort: 'CT State',
    tier: 'Amateur',
    tierLevel: 4,
    founded: 2013,
    firstSeason: 2013,
    stadium: 'Addison Park',
    stadiumAddress: 'Addison Park, Glastonbury, CT 06033',
    capacity: 400,
    primary: '#2E4057',
    secondary: '#E84855',
    colorName: 'Slate & Crimson',
    abbr: 'GLS',
    coach: 'Ryan Mulcahy',
    website: 'glastonburyfc.org',
    description: 'Glastonbury FC has been a pillar of central Connecticut soccer since 2013, competing in the CT State Open League and running a strong youth development program.',
    about: 'Based in the Connecticut River town of Glastonbury, the club serves the greater Hartford suburbs with competitive adult soccer and youth programs.',
    wins: 8, draws: 2, losses: 2,
    gf: 24, ga: 10,
    roster: [
      { name: 'Kyle Sheridan',    pos: 'MF', number: 10, nationality: 'USA' },
      { name: 'Mario Tavares',    pos: 'FW', number: 9,  nationality: 'Portugal' },
      { name: 'Ben Park',         pos: 'DF', number: 4,  nationality: 'USA' },
    ],
    recentResults: [
      { opponent: 'Waterbury Wolves',  home: true,  score: '2-2', result: 'D', date: 'Aug 4, 2026' },
      { opponent: 'Hartford Wanderers',home: false, score: '3-0', result: 'W', date: 'Jul 28, 2026' },
    ],
    upcoming: [
      { opponent: 'Norwich City CT',   home: true,  date: 'Aug 18, 2026', time: '6:00 PM' },
    ],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'norwalk-united',
    name: 'Norwalk United',
    city: 'Norwalk', state: 'CT',
    league: 'NPSL Northeast Conference',
    leagueShort: 'NPSL',
    tier: 'Amateur / Semi-Pro',
    tierLevel: 3,
    founded: 2019,
    firstSeason: 2019,
    stadium: 'Brien McMahon High School Stadium',
    stadiumAddress: '300 Highland Ave, Norwalk, CT 06854',
    capacity: 900,
    primary: '#FF6B35',
    secondary: '#1B1B2F',
    colorName: 'Orange & Navy',
    abbr: 'NRW',
    coach: 'Sofia Delgado',
    website: 'norwalkunitedsc.com',
    description: 'Norwalk United is a rising club in the NPSL Northeast Conference, bringing competitive semi-pro soccer to lower Fairfield County.',
    about: 'Founded in 2019, Norwalk United has grown quickly under strong local leadership and represents one of CT\'s fastest-growing soccer communities.',
    wins: 6, draws: 3, losses: 5,
    gf: 20, ga: 18,
    roster: [
      { name: 'Carlos Rivera',    pos: 'FW', number: 11, nationality: 'USA' },
      { name: 'Erik Lindqvist',   pos: 'MF', number: 7,  nationality: 'Sweden' },
      { name: 'Dre Thompson',     pos: 'GK', number: 1,  nationality: 'USA' },
    ],
    recentResults: [
      { opponent: 'Westport FC',       home: true,  score: '2-1', result: 'W', date: 'Aug 3, 2026' },
      { opponent: 'Bridgeport City SC', home: false, score: '0-1', result: 'L', date: 'Jul 27, 2026' },
    ],
    upcoming: [
      { opponent: 'Greenwich FC',      home: false, date: 'Aug 17, 2026', time: '3:00 PM' },
    ],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'hartford-wanderers',
    name: 'Hartford Wanderers',
    city: 'Hartford', state: 'CT',
    league: 'CT State Open League',
    leagueShort: 'CT State',
    tier: 'Amateur',
    tierLevel: 4,
    founded: 2016,
    firstSeason: 2016,
    stadium: 'Colt Park',
    stadiumAddress: 'Colt Park, Hartford, CT 06106',
    capacity: 600,
    primary: '#2B7CE9',
    secondary: '#FFD700',
    colorName: 'Blue & Yellow',
    abbr: 'HWD',
    coach: 'David Huang',
    website: 'hartfordwanderers.org',
    description: 'Hartford Wanderers is a community-focused amateur club in the CT State League, providing a home for soccer players across the Hartford area.',
    about: 'The Wanderers pride themselves on being an inclusive, community-first club with strong grassroots ties across Hartford\'s diverse neighborhoods.',
    wins: 5, draws: 2, losses: 5,
    gf: 16, ga: 18,
    roster: [
      { name: 'Luis Medina',      pos: 'FW', number: 9,  nationality: 'USA' },
      { name: 'Alex Chen',        pos: 'MF', number: 6,  nationality: 'USA' },
      { name: 'Jerome Davis',     pos: 'DF', number: 3,  nationality: 'USA' },
    ],
    recentResults: [
      { opponent: 'Waterbury Wolves',  home: false, score: '0-1', result: 'L', date: 'Aug 11, 2026' },
      { opponent: 'Glastonbury FC',    home: true,  score: '0-3', result: 'L', date: 'Jul 28, 2026' },
    ],
    upcoming: [
      { opponent: 'Greenwich FC',      home: true,  date: 'Aug 19, 2026', time: '6:00 PM' },
    ],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
];

// ── CT Youth Soccer Clubs ──────────────────────────────────────────────────
const CT_YOUTH_CLUBS = [
  {
    id: 'ct-rush',
    name: 'Connecticut Rush',
    city: 'Cromwell', state: 'CT',
    league: 'CJSA / ECRL / State Cup',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U9','U10','U11','U12','U13','U14','U15','U16','U17','U18','U19'],
    founded: 1990, firstSeason: 1990,
    stadium: 'Cromwell Soccer Complex',
    stadiumAddress: 'Cromwell, CT 06416',
    capacity: 500,
    primary: '#CC0000', secondary: '#FFFFFF',
    colorName: 'Red & White',
    abbr: 'CTR',
    coach: 'Director of Coaching',
    website: 'ctrush.com',
    instagram: '@connecticutrush', twitter: '@CTRush',
    description: 'Connecticut Rush is one of the largest and most established youth soccer organizations in Connecticut, offering elite competitive programs for players U9 through U19. The club competes in CJSA, ECRL, and USYS National Championships.',
    about: 'Founded in 1990, Connecticut Rush has developed hundreds of college-bound players and professionals. The club operates multiple boys and girls teams at every age level and is widely recognized as one of CT\'s premier development pathways.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: true },
  },
  {
    id: 'farmington-valley-sc',
    name: 'Farmington Valley SC',
    city: 'Farmington', state: 'CT',
    league: 'CJSA / CT State Cup',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 1978, firstSeason: 1978,
    stadium: 'Farmington Soccer Complex',
    stadiumAddress: 'Farmington, CT 06032',
    capacity: 400,
    primary: '#1A4E8A', secondary: '#FFFFFF',
    colorName: 'Royal Blue & White',
    abbr: 'FVS',
    coach: 'Director of Coaching',
    website: 'fvsc.net',
    instagram: '@farmingtonvalleysc', twitter: '',
    description: 'Farmington Valley Soccer Club is one of Connecticut\'s oldest and most respected youth organizations, serving communities in the Farmington Valley region including Farmington, Avon, Canton, Burlington, and Simsbury.',
    about: 'FVSC has been developing players since 1978, emphasizing long-term player development, team character, and a love of the game. The club fields competitive teams for both boys and girls at all age levels from U9 through U18.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'ct-fc-youth',
    name: 'Connecticut FC',
    city: 'Bloomfield', state: 'CT',
    league: 'ECRL / CJSA',
    leagueShort: 'ECRL',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U13','U14','U15','U16','U17','U18','U19'],
    founded: 2009, firstSeason: 2009,
    stadium: 'Covenant Prep School Fields',
    stadiumAddress: 'Bloomfield, CT 06002',
    capacity: 350,
    primary: '#003366', secondary: '#C9A227',
    colorName: 'Navy & Gold',
    abbr: 'CFC',
    coach: 'Director of Coaching',
    website: 'ctfc.net',
    instagram: '@connecticutfc', twitter: '@CTFC_Soccer',
    description: 'Connecticut FC is a competitive youth club offering ECRL and CJSA programs for players U13 through U19. The club is known for its college placement record and technical coaching staff.',
    about: 'CFC was founded to provide a high-level competitive environment for dedicated young players in the greater Hartford area. The club maintains strong relationships with college coaches and runs player identification programs across the state.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'eastern-ct-eagles',
    name: 'Eastern CT Eagles',
    city: 'Willimantic', state: 'CT',
    league: 'CJSA / CT State Cup',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 2001, firstSeason: 2001,
    stadium: 'Willimantic Youth Sports Complex',
    stadiumAddress: 'Willimantic, CT 06226',
    capacity: 300,
    primary: '#1F4E79', secondary: '#E2B04A',
    colorName: 'Navy & Gold',
    abbr: 'ECE',
    coach: 'Director of Coaching',
    website: 'easternctsc.com',
    instagram: '@easternctsc', twitter: '',
    description: 'Eastern CT Eagles serves the youth soccer community across eastern Connecticut, offering competitive travel programs for boys and girls U10 through U18 in the CJSA and state competitions.',
    about: 'One of the primary youth soccer organizations in eastern Connecticut, the Eagles draw players from Windham County and surrounding towns. The club focuses on developing technically sound players who compete at the regional and state level.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'west-hartford-sc',
    name: 'West Hartford SC',
    city: 'West Hartford', state: 'CT',
    league: 'CJSA',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U6','U7','U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 1969, firstSeason: 1969,
    stadium: 'Norfeldt / Charter Oak Park',
    stadiumAddress: 'West Hartford, CT 06107',
    capacity: 400,
    primary: '#005B8E', secondary: '#FFFFFF',
    colorName: 'Blue & White',
    abbr: 'WHY',
    coach: 'Director of Coaching',
    website: 'whsoccer.org',
    instagram: '@westhartsoccer', twitter: '',
    description: 'West Hartford Soccer Club is one of Connecticut\'s longest-running youth soccer organizations, serving West Hartford families since 1969 with recreational and competitive programs from U6 through U18.',
    about: 'WHSC is a community cornerstone offering both recreational leagues and competitive travel teams. The club\'s mission is to make the game accessible at all levels while providing pathways for those who wish to compete at higher levels.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'ridgefield-sc',
    name: 'Ridgefield Soccer Club',
    city: 'Ridgefield', state: 'CT',
    league: 'CJSA / Classic League',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 1974, firstSeason: 1974,
    stadium: 'Ridgefield Recreation Park',
    stadiumAddress: '195 Prospect Ridge Rd, Ridgefield, CT 06877',
    capacity: 350,
    primary: '#6B2737', secondary: '#C9A227',
    colorName: 'Maroon & Gold',
    abbr: 'RSC',
    coach: 'Director of Coaching',
    website: 'ridgefieldsc.org',
    instagram: '@ridgefieldsc', twitter: '',
    description: 'Ridgefield Soccer Club has been serving the Ridgefield youth community since 1974 with programs spanning recreational to competitive travel soccer for boys and girls.',
    about: 'RSC is one of Fairfield County\'s most established youth clubs, producing numerous college-level players over five decades. The club prides itself on community values, sportsmanship, and technical development.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'branford-sc',
    name: 'Branford Soccer Club',
    city: 'Branford', state: 'CT',
    league: 'CJSA',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 1972, firstSeason: 1972,
    stadium: 'Murphy Complex',
    stadiumAddress: 'Murphy Complex, Branford, CT 06405',
    capacity: 300,
    primary: '#004B23', secondary: '#FFFFFF',
    colorName: 'Green & White',
    abbr: 'BRN',
    coach: 'Director of Coaching',
    website: 'branfordsc.com',
    instagram: '@branfordsc', twitter: '',
    description: 'Branford Soccer Club is a community youth soccer organization on the Connecticut shoreline, offering recreational and competitive programs to Branford youth since 1972.',
    about: 'Branford SC serves the southern shoreline with both in-town recreational leagues and competitive travel teams, providing a pathway for players of all skill levels from beginners to high-level competitors.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'southington-sc',
    name: 'Southington Soccer Club',
    city: 'Southington', state: 'CT',
    league: 'CJSA / Classic League',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 1971, firstSeason: 1971,
    stadium: 'Southington Recreation Complex',
    stadiumAddress: 'Southington, CT 06489',
    capacity: 400,
    primary: '#2D6A4F', secondary: '#FFFFFF',
    colorName: 'Forest Green & White',
    abbr: 'SSC',
    coach: 'Director of Coaching',
    website: 'southingtonsoccer.org',
    instagram: '', twitter: '',
    description: 'Southington Soccer Club has been a staple of central Connecticut youth soccer since 1971, offering recreational and competitive programs for all ages.',
    about: 'SSC operates one of the most comprehensive youth programs in the greater Hartford suburbs, with both in-town leagues and travel teams competing in the CJSA and Classic League across Connecticut.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'oakwood-sc',
    name: 'Oakwood Soccer Club',
    city: 'Enfield', state: 'CT',
    league: 'CJSA',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U8','U9','U10','U11','U12','U13','U14','U15','U16','U17'],
    founded: 1985, firstSeason: 1985,
    stadium: 'Enfield Community Sports Complex',
    stadiumAddress: 'Enfield, CT 06082',
    capacity: 350,
    primary: '#5C4033', secondary: '#FFFFFF',
    colorName: 'Brown & White',
    abbr: 'OAK',
    coach: 'Director of Coaching',
    website: 'oakwoodsc.com',
    instagram: '@oakwoodscct', twitter: '',
    description: 'Oakwood Soccer Club is a northern Connecticut youth organization based in Enfield, offering competitive CJSA programs for players U8 through U17.',
    about: 'Serving communities in the Springfield/Hartford corridor including Enfield, Suffield, and East Windsor, Oakwood SC provides a local high-quality soccer environment for youth players seeking competitive opportunities without needing to travel to larger urban centers.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'shoreline-sc',
    name: 'Shoreline Soccer Club',
    city: 'Madison', state: 'CT',
    league: 'CJSA / Classic League',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 1988, firstSeason: 1988,
    stadium: 'Madison Sports Complex',
    stadiumAddress: 'Madison, CT 06443',
    capacity: 350,
    primary: '#005F73', secondary: '#FFFFFF',
    colorName: 'Teal & White',
    abbr: 'SSL',
    coach: 'Director of Coaching',
    website: 'shorelinesc.com',
    instagram: '@shorelinesc', twitter: '',
    description: 'Shoreline Soccer Club serves the Connecticut shoreline communities of Madison, Guilford, North Branford, and Clinton with competitive youth soccer programs from U9 through U18.',
    about: 'Founded in 1988 to serve shoreline communities, SSC has grown into one of the premier youth clubs along the Connecticut coast. The club emphasizes quality coaching, player development, and fostering a lifelong love of the game.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
];

// ── CT Competitive / EDP Youth Clubs (real contact info from club websites) ──
const CT_EDP_CLUBS = [
  {
    id: 'beachside-sc',
    name: 'Beachside Soccer Club',
    city: 'Norwalk', state: 'CT',
    league: 'MLS NEXT / EDP',
    leagueShort: 'MLS NEXT',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U13','U14','U15','U16','U17','U18','U19'],
    founded: 2003, firstSeason: 2003,
    stadium: 'Gallagher Field / Strawberry Hill',
    stadiumAddress: '10 Prospect St Unit 4, Norwalk, CT 06850',
    capacity: 400,
    primary: '#002868', secondary: '#FFFFFF',
    colorName: 'Navy & White',
    abbr: 'BSC',
    coach: 'Mickey Kydes',
    contactEmail: 'greg@beachside.soccer',
    contactPhone: '(203) 852-6969',
    contactUrl: 'https://beachsidesoccer.org',
    tryoutsUrl: 'https://beachsidesoccer.org/tryouts-2/',
    tryoutsNote: 'Open talent ID tryouts held seasonally for all competitive age groups. Check website for current session dates.',
    tournaments: ['MLS NEXT National Competitions','Capelli Sport International Tour (Denmark)'],
    website: 'beachsidesoccer.org',
    description: 'Beachside Soccer Club is one of Connecticut\'s most elite youth organizations, competing at the MLS NEXT level — the highest developmental league in U.S. youth soccer. The club has produced players who have gone on to college and professional careers.',
    about: 'Founded in Norwalk under Coaching Director Mickey Kydes, Beachside emphasizes high-level training, discipline, and commitment to excellence. The club runs Juniors developmental programs and competitive squads from U13 through U19 for both boys and girls.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'ginga-fc',
    name: 'Ginga FC',
    city: 'Woodbridge', state: 'CT',
    league: 'MLS NEXT / EDP / GA Aspire',
    leagueShort: 'MLS NEXT',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U7','U8','U9','U10','U11','U12','U13','U14','U15','U16','U17'],
    founded: 2010, firstSeason: 2010,
    stadium: 'Everson Soccer Complex',
    stadiumAddress: '21 South Bradley Rd, Woodbridge, CT 06525',
    capacity: 500,
    primary: '#228B22', secondary: '#FFD700',
    colorName: 'Forest Green & Gold',
    abbr: 'GNG',
    coach: 'Director of Coaching',
    contactEmail: 'GingaFC.CT@gmail.com',
    contactPhone: '(203) 298-4763',
    contactUrl: 'https://gingafc.com',
    tryoutsUrl: 'https://gingafc.com',
    tryoutsNote: 'Supplemental tryouts and ID clinics available year-round. Contact club for current openings by age group. Free ID clinics offered periodically.',
    tournaments: ['MLS NEXT League Play','GA Aspire Championships','EDP Spring/Fall Tournaments'],
    website: 'gingafc.com',
    description: 'Ginga FC operates across four Connecticut locations (Woodbridge, Hamden, Madison, Southbury) competing in MLS NEXT (boys), GA Aspire (girls), and EDP. The club is known for its Brazilian-inspired style and technical development approach.',
    about: 'With branches spanning from Woodbridge to the shoreline and Southbury, Ginga FC has grown into one of CT\'s most geographically accessible elite clubs. Boys teams compete in MLS NEXT and National League; girls in GA Aspire, DPL, and EDP.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'sporting-ct',
    name: 'Sporting CT',
    city: 'Middletown', state: 'CT',
    league: 'EDP / N1 / WPSL',
    leagueShort: 'EDP',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U12','U13','U14','U15','U16','U17','U19'],
    founded: 2008, firstSeason: 2008,
    stadium: 'Sporting CT Complex (CCR)',
    stadiumAddress: '395 Country Club Rd, Middletown, CT 06457',
    capacity: 600,
    primary: '#0C2340', secondary: '#C8A84B',
    colorName: 'Navy & Gold',
    abbr: 'SCT',
    coach: 'Goran Vasic',
    contactEmail: 'Goran@sportingct.com',
    contactPhone: '',
    contactUrl: 'https://sportingct.com/contact-us/',
    tryoutsUrl: 'https://sportingct.leagueapps.com/leagues/soccer/4471989-sporting-ct-tryouts-2025-2026-season',
    tryoutsNote: '2026/27 supplemental tryouts open via LeagueApps. Boys and girls programs from U12–U19. Also fields U-23 Men and WPSL Women.',
    tournaments: ['Sporting CT Spring Shootout (April)','Memorial Showcase (Memorial Day Weekend)','Gia\'s Memorial Classic'],
    website: 'sportingct.com',
    description: 'Sporting CT is a comprehensive youth and adult soccer organization based at their own complex in Middletown. The club competes in EDP, N1 League, NECSL, WPSL (women), and NAL, offering elite pathways from U12 through adult.',
    about: 'Under Executive Director Goran Vasic, Sporting CT focuses on the holistic development of players. The club hosts several of Connecticut\'s top tournaments and has grown to include a U-23 men\'s program and WPSL women\'s team.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'fsa-fc',
    name: 'FSA FC',
    city: 'Farmington', state: 'CT',
    league: 'ECNL / ECRL',
    leagueShort: 'ECNL',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U9','U10','U11','U12','U13','U14','U15','U16','U17','U18','U19'],
    founded: 2009, firstSeason: 2009,
    stadium: 'Farmington Sports Arena',
    stadiumAddress: '11 Executive Dr Suite 202, Farmington, CT 06032',
    capacity: 800,
    primary: '#00539C', secondary: '#FFB81C',
    colorName: 'Royal Blue & Gold',
    abbr: 'FSA',
    coach: 'Director of Coaching',
    contactEmail: 'clubadmin@fsafcunited.com',
    contactPhone: '(860) 404-5789',
    contactUrl: 'https://fsafc.com/contact-us/',
    tryoutsUrl: 'https://fsafc.com/tryouts/',
    tryoutsNote: 'Annual tryouts for all ECNL and ECRL age groups. Pre-ECNL ID Clinics held in spring. Check website for current schedule.',
    tournaments: ['FSA Columbus Cup (Oct, U9–U15)','Northeast Spring College Showcase (Mar, U15–U19)','ECNL Playoffs'],
    website: 'fsafc.com',
    description: 'FSA FC (Farmington Sports Arena Football Club) competes in the Elite Clubs National League (ECNL) — one of the highest-level youth soccer leagues in the country. Based at a 130,000 sq ft indoor facility with 9 outdoor fields, FSA FC serves U9 through U19.',
    about: 'Founded in 2009, FSA FC rapidly rose to become one of Connecticut\'s premier youth clubs. The club hosts the FSA Columbus Cup each fall and the Northeast Spring College Showcase, which draws college coaches from across the country.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'vale-sc',
    name: 'Vale Sports Club',
    city: 'Middletown', state: 'CT',
    league: 'EDP / MLS GO',
    leagueShort: 'EDP',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U4','U5','U6','U7','U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 2012, firstSeason: 2012,
    stadium: 'The Forge / Vale Fieldhouse',
    stadiumAddress: '49 Randolph Rd, Middletown, CT 06457',
    capacity: 600,
    primary: '#6A0DAD', secondary: '#FFFFFF',
    colorName: 'Purple & White',
    abbr: 'VSC',
    coach: 'Director of Coaching',
    contactEmail: 'contact@valesc.com',
    contactPhone: '(475) 331-5243',
    contactUrl: 'https://valesc.com',
    tryoutsUrl: 'https://valesc.com/easttryouts/',
    tryoutsNote: 'Each Vale location (Middletown, East, West, North/Windsor) holds separate tryouts. Check valesc.com for location-specific schedules.',
    tournaments: ['Vale Fieldhouse Indoor Tournaments','MLS GO League Competitions'],
    website: 'valesc.com',
    description: 'Vale Sports Club operates at multiple Connecticut locations (Middletown, East, West, and North/Windsor) offering programs from grassroots ages 3+ through competitive U18. The club plays in EDP and the MLS GO in-house league system.',
    about: 'Vale SC features two major facilities — The Forge (49 Randolph Rd) and the Vale Fieldhouse (1280 Newfield St) in Middletown — and runs competitive boys and girls programs alongside youth development, PASS skill training, and adult leagues.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'ole-fc',
    name: 'Ole FC',
    city: 'Monroe', state: 'CT',
    league: 'EDP / CFC-Ole',
    leagueShort: 'EDP',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U3','U4','U5','U6','U7','U8','U9','U10','U11','U12','U13','U14'],
    founded: 2004, firstSeason: 2004,
    stadium: 'Ole Training Center (OTC)',
    stadiumAddress: 'Monroe, CT 06468',
    capacity: 300,
    primary: '#D4202C', secondary: '#FFD700',
    colorName: 'Red & Gold',
    abbr: 'OLE',
    coach: 'Rodrigo Nunes',
    contactEmail: 'sam.olesoccer@gmail.com',
    contactPhone: '(203) 873-0309',
    contactUrl: 'https://olesoccerct.com/contact-us/',
    tryoutsUrl: 'https://olesoccerct.com/girlstryout/',
    tryoutsNote: 'Tryouts and supplemental placement available for girls and boys. The club also partners with CFC for travel and premier opportunities (2026/27 CFC tryouts available).',
    tournaments: ['Ole Summer Clinics','CFC-Ole League Play'],
    website: 'olesoccerct.com',
    description: 'Ole FC, founded in Monroe in 2004 by Rodrigo Nunes, offers developmental programs from age 18 months through U14. The club runs the Ole Developmental Academy (ODA) and partners with Connecticut FC for higher-level travel opportunities.',
    about: 'Known for its welcoming community culture and wide range of age-appropriate programs, Ole FC operates the Ole Training Center in Monroe and serves families across southwestern Connecticut with Stars programs, goalkeeping clinics, and adult leagues.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'ct-rush-select',
    name: 'CT Rush (Northeast Rush)',
    city: 'Southbury', state: 'CT',
    league: 'MLS NEXT / EDP',
    leagueShort: 'MLS NEXT',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U3','U4','U5','U6','U7','U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18','U19'],
    founded: 1997, firstSeason: 1997,
    stadium: 'Northeast Rush Regional Facility',
    stadiumAddress: 'Southbury, CT 06488',
    capacity: 500,
    primary: '#CC0000', secondary: '#FFFFFF',
    colorName: 'Red & White',
    abbr: 'NER',
    coach: 'Director of Coaching',
    contactEmail: 'info@northeastrush.com',
    contactPhone: '',
    contactUrl: 'https://northeastrush.com',
    tryoutsUrl: 'https://northeastrush.com/tryouts-2025',
    tryoutsNote: 'CT Rush operates five regional CT programs: CT Central, Northeast, South, Southeast, and South Central. CT Select teams compete in MLS NEXT. Check northeastrush.com/join-the-rush for team placement.',
    tournaments: ['MLS NEXT Competitions','Rush Cup','USYS Regional Championships'],
    website: 'northeastrush.com/connecticut',
    description: 'CT Rush (part of Northeast Rush) is one of the largest youth soccer organizations in New England, with five regional CT programs and an elite CT Select program that competes in MLS NEXT. The club serves players from age 3 through high school.',
    about: 'Northeast Rush CT operates CT Central, CT Northeast, CT South, CT Southeast, and CT South Central programs, plus an advanced CT Select pathway that joined MLS NEXT for the 2025-2026 season. The club emphasizes age-appropriate coaching and long-term player development.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: true },
  },
  {
    id: 'inter-ct-fc',
    name: 'Inter Connecticut FC',
    city: 'Easton', state: 'CT',
    league: 'EDP / USL',
    leagueShort: 'EDP',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U6','U7','U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18','U19'],
    founded: 2005, firstSeason: 2005,
    stadium: 'Easton-Redding Field Complex',
    stadiumAddress: 'Easton, CT 06612',
    capacity: 400,
    primary: '#003DA5', secondary: '#000000',
    colorName: 'Royal Blue & Black',
    abbr: 'ICT',
    coach: 'Stephen Bell',
    contactEmail: 'info@interctfc.com',
    contactPhone: '',
    contactUrl: 'https://www.interctfc.com',
    tryoutsUrl: 'https://www.interctfc.com/tryouts',
    tryoutsNote: 'Annual tryouts held for all travel age groups. Micro Soccer program for youngest players. Litchfield Hills branch also holds separate sessions. Contact stephen@interctfc.com or info@interctfc.com.',
    tournaments: ['EDP Spring/Fall Tournaments','Inter CT Invitational'],
    website: 'interctfc.com',
    description: 'Inter Connecticut FC is a major EDP club serving Fairfield and Litchfield County with pathways from Micro Soccer (U6) through U19 and beyond. The club offers academy, travel, and premier programs and has a separate Litchfield Hills branch.',
    about: 'Inter CT FC provides a complete soccer pathway for Connecticut players. Director of Coaching Stephen Bell oversees competitive programs, while the Litchfield Hills branch (directed by Dave Shannon) serves the northwest corner of the state.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'cfc',
    name: 'Connecticut Football Club',
    city: 'Bethany', state: 'CT',
    league: 'ECNL / ECRL / N1',
    leagueShort: 'ECNL',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U3','U4','U5','U6','U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18','U19'],
    founded: 2000, firstSeason: 2000,
    stadium: 'CFC Park',
    stadiumAddress: 'Bethany, CT 06524',
    capacity: 600,
    primary: '#00205B', secondary: '#C8102E',
    colorName: 'Navy & Red',
    abbr: 'CFC',
    coach: 'Director of Coaching',
    contactEmail: 'info@connecticutfootballclub.com',
    contactPhone: '',
    contactUrl: 'https://connecticutfootballclub.org',
    tryoutsUrl: 'https://connecticutfootballclub.org',
    tryoutsNote: 'CFC fields statewide teams in ECNL, ECRL, and N1 League. Use the "Find My CFC Team" form on the website to be matched with the right program for your location and age group.',
    tournaments: ['ECNL National Event','ECRL Regional Playoffs','CFC Summer Summit'],
    website: 'connecticutfootballclub.org',
    description: 'Connecticut Football Club (CFC) is a statewide ECNL club offering one of Connecticut\'s highest-level youth pathways for both boys and girls. Programs include Little Kickers (U3–U6), CFC Bethany Academy, and full ECNL/ECRL competitive programs.',
    about: 'CFC maintains CFC Park in Bethany as its primary facility and fields teams across CT through regional programs including CFC North, CFC South, CFC Valley, and CFC Ole. The club competes in ECNL — one of the top youth leagues in the US.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'trumbull-united-sc',
    name: 'Trumbull United SC',
    city: 'Trumbull', state: 'CT',
    league: 'EDP / CJSA',
    leagueShort: 'EDP',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 2005, firstSeason: 2005,
    stadium: 'InSports Centers',
    stadiumAddress: '29 Trefoil Dr, Trumbull, CT 06611',
    capacity: 350,
    primary: '#D40000', secondary: '#FFFFFF',
    colorName: 'Red & White',
    abbr: 'TUS',
    coach: 'Director of Coaching',
    contactEmail: 'trumbullunitedsoccerclub@gmail.com',
    contactPhone: '',
    contactUrl: 'https://www.trumbullunited.com',
    tryoutsUrl: 'https://www.trumbullunited.com',
    tryoutsNote: 'Annual tryouts (May) for Grades 2–8 and High School. Both sessions required. Location: InSports Centers, 29 Trefoil Drive, Trumbull. Check website for exact dates.',
    tournaments: ['EDP Spring/Fall Tournaments','CJSA State Cup'],
    website: 'trumbullunited.com',
    description: 'Trumbull United SC offers Academy, Travel, and Premier soccer programs for players in Grades 2–8 and High School in Trumbull and surrounding Fairfield County communities.',
    about: 'Based at InSports Centers in Trumbull, the club provides a structured developmental path from recreational through premier competition. Travel serves as a stepping stone to the Premier program, which competes at the highest EDP and state levels.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'fairfield-united-sa',
    name: 'Fairfield United SA',
    city: 'Fairfield', state: 'CT',
    league: 'CJSA/SWD',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U8','U9','U10','U11','U12','U13','U14','U15'],
    founded: 1985, firstSeason: 1985,
    stadium: 'Fairfield Recreation Fields',
    stadiumAddress: 'Fairfield, CT 06824',
    capacity: 300,
    primary: '#B22222', secondary: '#FFFFFF',
    colorName: 'Crimson & White',
    abbr: 'FUS',
    coach: 'Director of Coaching',
    contactEmail: 'fusaboard@gmail.com',
    contactPhone: '',
    contactUrl: 'https://www.fairfieldunited.com',
    tryoutsUrl: 'https://www.fairfieldunited.com/programs/tryouts',
    tryoutsNote: 'Competitive travel soccer for Fairfield residents in grades U8–U14/U15. Tryout schedules posted on website and communicated via email/PlayMetrics.',
    tournaments: ['CJSA State Cup','SWD District Championships'],
    website: 'fairfieldunited.com',
    description: 'Fairfield United Soccer Association provides competitive travel soccer exclusively for Fairfield residents, competing in the CJSA Southwestern District. The club focuses on player development within a town-specific community program.',
    about: 'One of Fairfield County\'s long-standing youth organizations, FUSA ensures Fairfield residents have access to quality competitive soccer without leaving their town program. The club develops players from U8 through high school levels.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'ac-connecticut',
    name: 'AC Connecticut',
    city: 'Newtown', state: 'CT',
    league: 'EDP',
    leagueShort: 'EDP',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 2010, firstSeason: 2010,
    stadium: 'Newtown Youth Academy Fields',
    stadiumAddress: 'Newtown, CT 06470',
    capacity: 350,
    primary: '#1A1A6E', secondary: '#FFFFFF',
    colorName: 'Navy & White',
    abbr: 'ACC',
    coach: 'Director of Coaching',
    contactEmail: '',
    contactPhone: '',
    contactUrl: 'https://acconnecticut.com',
    tryoutsUrl: 'https://acconnecticut.com',
    tryoutsNote: 'Competitive EDP teams for boys and girls. Visit acconnecticut.com for current tryout schedule and registration.',
    tournaments: ['EDP Spring/Fall Championships'],
    website: 'acconnecticut.com',
    description: 'AC Connecticut is a competitive EDP club based in Newtown, serving the Newtown, Sandy Hook, Monroe, and surrounding communities with high-level travel soccer for boys and girls.',
    about: 'AC Connecticut competes across multiple EDP divisions and provides a pathway for dedicated players in the greater Newtown area. The club focuses on technical development and competitive preparation at every age level.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'revolution-united-fc',
    name: 'Revolution United FC',
    city: 'Naugatuck', state: 'CT',
    league: 'EDP / CJSA',
    leagueShort: 'EDP',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 2008, firstSeason: 2008,
    stadium: 'Naugatuck Recreation Complex',
    stadiumAddress: 'Naugatuck, CT 06770',
    capacity: 300,
    primary: '#002395', secondary: '#ED2939',
    colorName: 'Blue & Red',
    abbr: 'RUF',
    coach: 'Director of Coaching',
    contactEmail: '',
    contactPhone: '',
    contactUrl: 'https://www.revolutionunitedfc.com',
    tryoutsUrl: 'https://www.revolutionunitedfc.com',
    tryoutsNote: 'Tryouts held for all EDP and CJSA competitive teams. Visit revolutionunitedfc.com for current schedule.',
    tournaments: ['EDP Connecticut Championships','CJSA State Cup'],
    website: 'revolutionunitedfc.com',
    description: 'Revolution United FC serves the Naugatuck Valley with competitive EDP and CJSA soccer programs for boys and girls from U8 through U18.',
    about: 'RUFC provides high-quality competitive soccer in the Naugatuck Valley, drawing players from Naugatuck, Beacon Falls, Seymour, Derby, and surrounding communities. The club competes in EDP and the CJSA State Cup.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'yankee-united-fc',
    name: 'Yankee United FC',
    city: 'Enfield', state: 'CT',
    league: 'EDP / CJSA',
    leagueShort: 'EDP',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 1999, firstSeason: 1999,
    stadium: 'Yankee Soccer Complex',
    stadiumAddress: 'Enfield, CT 06082',
    capacity: 400,
    primary: '#003087', secondary: '#C8102E',
    colorName: 'Navy & Red',
    abbr: 'YUF',
    coach: 'Director of Coaching',
    contactEmail: '',
    contactPhone: '',
    contactUrl: 'http://www.yankeeunited.com',
    tryoutsUrl: 'http://www.yankeeunited.com',
    tryoutsNote: 'EDP and CJSA competitive teams for boys and girls. Visit yankeeunited.com for tryout information.',
    tournaments: ['EDP Championships','CJSA State Cup','Yankee United Invitational'],
    website: 'yankeeunited.com',
    description: 'Yankee United FC is a long-established EDP club in north-central Connecticut, serving the greater Enfield and Springfield corridor with boys and girls competitive programs from U8 through U18.',
    about: 'One of CT\'s more established EDP clubs, Yankee United draws players from Enfield, Windsor Locks, Suffield, East Windsor, and the Springfield border area. The club competes in EDP and CJSA state competitions.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'northeast-united-sc',
    name: 'Northeast United SC',
    city: 'Tolland', state: 'CT',
    league: 'EDP / CJSA',
    leagueShort: 'EDP',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 2003, firstSeason: 2003,
    stadium: 'Tolland Recreation Complex',
    stadiumAddress: 'Tolland, CT 06084',
    capacity: 300,
    primary: '#006400', secondary: '#FFD700',
    colorName: 'Green & Gold',
    abbr: 'NUS',
    coach: 'Director of Coaching',
    contactEmail: '',
    contactPhone: '',
    contactUrl: 'https://www.northeastunited.org',
    tryoutsUrl: 'https://www.northeastunited.org',
    tryoutsNote: 'EDP competitive teams for boys and girls. Serving Tolland, Coventry, Vernon, and eastern CT communities. Visit northeastunited.org for tryout schedule.',
    tournaments: ['EDP Tournaments','CJSA State Cup'],
    website: 'northeastunited.org',
    description: 'Northeast United SC serves eastern Connecticut communities including Tolland, Coventry, and Vernon with EDP and CJSA competitive soccer programs.',
    about: 'NUSC provides competitive youth soccer for the northeastern CT region, offering boys and girls programs from U8 through U18 in EDP and CJSA competition.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'shoreline-united-sc',
    name: 'Shoreline United SC',
    city: 'East Haddam', state: 'CT',
    league: 'EDP / CJSA',
    leagueShort: 'EDP',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 2006, firstSeason: 2006,
    stadium: 'Haddam-Killingworth Fields',
    stadiumAddress: 'East Haddam, CT 06423',
    capacity: 300,
    primary: '#0077C2', secondary: '#FFFFFF',
    colorName: 'Blue & White',
    abbr: 'SUS',
    coach: 'Director of Coaching',
    contactEmail: '',
    contactPhone: '',
    contactUrl: 'https://www.shorelineunitedsoccerclub.com',
    tryoutsUrl: 'https://www.shorelineunitedsoccerclub.com',
    tryoutsNote: 'EDP and CJSA teams for the Connecticut River and shoreline region. Serving communities including East Haddam, Haddam, Killingworth, Chester, and Deep River.',
    tournaments: ['EDP Connecticut Tournaments','CJSA State Cup'],
    website: 'shorelineunitedsoccerclub.com',
    description: 'Shoreline United SC serves the lower Connecticut River valley and shoreline with competitive EDP and CJSA soccer for boys and girls.',
    about: 'Shoreline United draws players from the lower Connecticut River corridor — East Haddam, Haddam, Chester, Deep River, Killingworth, and surrounding communities — providing a local competitive option for shoreline families.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
];

// Combined array for pages that need all clubs
const ALL_CLUBS = [...CT_CLUBS, ...CT_YOUTH_CLUBS, ...CT_EDP_CLUBS];

function getClubById(id) {
  return ALL_CLUBS.find(c => c.id === id) || null;
}

function clubPts(c) { return c.wins * 3 + c.draws; }
function clubGD(c)  { return c.gf - c.ga; }

function tierBadgeHtml(tier) {
  if (tier === 'Professional')        return '<span style="background:rgba(245,168,0,.14);color:#F5A800;border:1px solid rgba(245,168,0,.3);font-size:.62rem;font-weight:700;letter-spacing:.07em;text-transform:uppercase;padding:3px 9px;border-radius:6px;">Pro</span>';
  if (tier === 'Semi-Professional')   return '<span style="background:rgba(43,124,233,.14);color:#5BA3FF;border:1px solid rgba(43,124,233,.28);font-size:.62rem;font-weight:700;letter-spacing:.07em;text-transform:uppercase;padding:3px 9px;border-radius:6px;">Semi-Pro</span>';
  if (tier === 'Youth')               return '<span style="background:rgba(92,221,139,.12);color:#5CDD8B;border:1px solid rgba(92,221,139,.25);font-size:.62rem;font-weight:700;letter-spacing:.07em;text-transform:uppercase;padding:3px 9px;border-radius:6px;">Youth</span>';
  return '<span style="background:rgba(255,255,255,.08);color:rgba(255,255,255,.55);border:1px solid rgba(255,255,255,.12);font-size:.62rem;font-weight:700;letter-spacing:.07em;text-transform:uppercase;padding:3px 9px;border-radius:6px;">Amateur</span>';
}
