// Real CT Soccer clubs data — used across all pages
const CT_CLUBS = [
  {
    id: 'hartford-athletic',
    name: 'Hartford Athletic',
    city: 'Hartford', state: 'CT',
    league: 'USL Championship',
    leagueShort: 'USL-C',
    tier: 'Professional',
    tierLevel: 1,
    founded: 2018,
    firstSeason: 2019,
    stadium: 'Trinity Health Stadium',
    stadiumAddress: '351 Reserve Rd, Hartford, CT 06114',
    capacity: 5500,
    primary: '#1B2A4A',
    secondary: '#F5A800',
    colorName: 'Navy & Gold',
    abbr: 'HFD',
    coach: 'Harry Watling',
    website: 'hartfordathletic.com',
    sportsDbId: '138877',
    instagram: '@hartfordathletic',
    twitter: '@HFDAthletic',
    description: 'Hartford Athletic is a professional soccer club competing in USL Championship, the second division of American soccer. Founded in 2018 with their first season in 2019, they are Connecticut\'s only professional soccer club and play at Trinity Health Stadium (formerly Dillon Stadium) in Hartford.',
    about: 'Hartford Athletic was founded as part of a grassroots effort to bring professional soccer back to Connecticut\'s capital. The club quickly built a passionate local fanbase and competes against top USL Championship clubs across the United States.',
    wins: 4, draws: 9, losses: 5,
    gf: 13, ga: 17,
    roster: [
      { name: 'Danny Barrera',    pos: 'MF', number: 10, nationality: 'USA' },
      { name: 'Paulo Jr.',        pos: 'FW', number: 9,  nationality: 'USA' },
      { name: 'Nicky Hernandez',  pos: 'MF', number: 8,  nationality: 'USA' },
      { name: 'Carlos Merancio',  pos: 'DF', number: 4,  nationality: 'USA' },
      { name: 'Luca Petrasso',    pos: 'MF', number: 11, nationality: 'Canada' },
    ],
    recentResults: [
      { opponent: 'Indy Eleven',       home: false, score: '1-1', result: 'D', date: 'Aug 9, 2026' },
      { opponent: 'Loudoun United FC', home: false, score: '0-2', result: 'L', date: 'Aug 1, 2026' },
      { opponent: 'Phoenix Rising FC', home: false, score: '0-0', result: 'D', date: 'Jul 25, 2026' },
    ],
    upcoming: [
      { opponent: 'Miami FC',              home: true,  date: 'Aug 15, 2026', time: '7:00 PM' },
      { opponent: 'Birmingham Legion FC',  home: true,  date: 'Aug 29, 2026', time: '7:00 PM' },
      { opponent: 'Charleston Battery',    home: false, date: 'Sep 2, 2026',  time: 'TBD' },
    ],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: true },
  },
  {
    id: 'ct-united-fc',
    name: 'CT United FC',
    city: 'Bridgeport', state: 'CT',
    league: 'MLS Next Pro',
    leagueShort: 'MLS NEXT Pro',
    tier: 'Professional',
    tierLevel: 1,
    founded: 2024,
    firstSeason: 2026,
    stadium: 'Morrone Stadium (Storrs) / Reese Stadium (New Haven)',
    stadiumAddress: 'Home matches rotate around Connecticut while a permanent waterfront stadium is developed in Bridgeport',
    capacity: 3000,
    primary: '#4B2E6B',
    secondary: '#2D6FA3',
    colorName: 'Park City Purple & Azure Breeze Blue',
    abbr: 'CTU',
    coach: 'Shavar Thomas',
    website: 'ctunited.com',
    twitter: '@CTUnitedFC',
    instagram: '@ctunitedfc',
    description: 'CT United FC is Connecticut\'s first MLS Next Pro club, the third tier of the American soccer pyramid and MLS\'s official player-development league. Founded in 2024 and based in Bridgeport, the club is owned by Connecticut Sports Group and made its debut in March 2026.',
    about: 'CT United FC is building toward a permanent waterfront stadium on a former dog-racing track site in Bridgeport, playing its inaugural home matches at UConn\'s Morrone Stadium and Yale\'s Reese Stadium in the meantime. Head coach Shavar Thomas, a former Jamaican national team captain, leads the club\'s first-team roster and its MLS Next academy program.',
    wins: 10, draws: 2, losses: 9,
    gf: 42, ga: 43,
    roster: [],
    recentResults: [
      { opponent: 'New England Revolution II', home: true, score: '1-2', result: 'L', date: 'Aug 9, 2026' },
      { opponent: 'Orlando City B',            home: true, score: '4-2', result: 'W', date: 'Aug 1, 2026' },
      { opponent: 'Columbus Crew 2',           home: true, score: '2-1', result: 'W', date: 'Jul 26, 2026' },
    ],
    upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'new-haven-united-fc',
    name: 'New Haven United FC',
    city: 'New Haven', state: 'CT',
    league: 'NPSL (National Premier Soccer League)',
    leagueShort: 'NPSL',
    tier: 'Amateur / Semi-Pro',
    tierLevel: 3,
    founded: 2025,
    firstSeason: 2025,
    stadium: 'Reese Stadium',
    stadiumAddress: 'Reese Stadium, Yale University, New Haven, CT',
    capacity: 3000,
    primary: '#00205B',
    secondary: '#FFFFFF',
    colorName: 'Navy & White',
    abbr: 'NHU',
    coach: 'Kledis Capollari',
    website: 'newhavenunited.com',
    instagram: '@NewhavenunitedFC', twitter: '@nhunitedfc',
    description: 'New Haven United FC is a semi-professional club in the NPSL\'s Northeast Region, North Atlantic Conference. Founded in 2025 as the spiritual successor to the Elm City Express, the club plays at Yale\'s Reese Stadium and features players from 14 different countries.',
    about: 'Led by president Jason Price and head coach Kledis Capollari — a former Hartford Athletic assistant and youth development lead — New Haven United reached the NPSL conference final in its debut 2025 season and won the North Atlantic Conference outright in 2026 before falling to eventual national runner-up Bristol Rhythm AFC in the club\'s first-ever National Semifinal appearance.',
    wins: 6, draws: 2, losses: 2,
    gf: 0, ga: 0,
    roster: [],
    recentResults: [
      { opponent: 'Bristol Rhythm AFC',      home: false, score: '0-2', result: 'L', date: 'Jul 25, 2026' },
      { opponent: 'West Chester United SC', home: false, score: '4-2', result: 'W', date: 'Jul 19, 2026' },
    ],
    upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'ac-connecticut',
    name: 'AC Connecticut',
    city: 'Hartford', state: 'CT',
    league: 'USL League Two',
    leagueShort: 'USL2',
    tier: 'Semi-Professional',
    tierLevel: 2,
    founded: 2011,
    firstSeason: 2012,
    stadium: 'Trinity Health Stadium',
    stadiumAddress: '351 Reserve Rd, Hartford, CT 06114',
    capacity: 5500,
    primary: '#1B3A6B',
    secondary: '#0D0D0D',
    colorName: 'Blue, Black & White',
    abbr: 'ACC',
    coach: 'Alex Harrison',
    website: 'acconnecticut.com',
    sportsDbId: '142166',
    description: 'AC Connecticut is an amateur men\'s club playing in USL League Two, the fourth tier of the American soccer pyramid and the country\'s top summer league for college-eligible players. Founded in 2011 as CFC Azul before rebranding in 2014, the club now shares a home ground with Hartford Athletic under a 2021 partnership.',
    about: 'Owned by Peter D\'Amico and general-managed by Robin Schuppert, AC Connecticut sits atop a 70-plus team youth organization and is regarded as Connecticut\'s longest-running organized senior soccer franchise outside of Hartford Athletic. The club competes annually in USL League Two\'s Northeast Division.',
    wins: 3, draws: 0, losses: 11,
    gf: 18, ga: 29,
    roster: [],
    recentResults: [],
    upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'connecticut-rush-usl2',
    name: 'CT Rush (USL2)',
    apiTeamName: 'Connecticut Rush',
    city: 'Southbury', state: 'CT',
    league: 'USL League Two',
    leagueShort: 'USL2',
    tier: 'Semi-Professional',
    tierLevel: 2,
    founded: 2012,
    firstSeason: 2026,
    stadium: 'TBD (Northeast Rush regional facilities)',
    stadiumAddress: 'Southern Middlesex County, CT',
    capacity: 1000,
    primary: '#CC0000',
    secondary: '#FFFFFF',
    colorName: 'Red & White',
    abbr: 'CTR',
    coach: 'Director of Coaching',
    website: 'northeastrush.com/ctusl2',
    sportsDbId: '154909',
    description: 'Connecticut Rush is the senior men\'s USL League Two side fielded by the Northeast Rush youth organization, joining the league\'s Northeast Division for its debut season in 2026.',
    about: 'Part of the wider Northeast Rush family that runs CT Rush youth programming across five regional CT branches, the USL League Two senior side plays out of southern Middlesex County and draws its roster from top college and academy-level talent across the state. This connects Northeast Rush\'s CT youth pipeline directly to college-eligible, semi-professional competition.',
    wins: 4, draws: 2, losses: 8,
    gf: 19, ga: 26,
    roster: [],
    recentResults: [],
    upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
];

// ── CT Youth Soccer Clubs ──────────────────────────────────────────────────
const CT_YOUTH_CLUBS = [
  {
    id: 'ct-rush',
    name: 'Connecticut Rush',
    city: 'Cromwell', state: 'CT',
    league: 'CJSA / ECRL / State Cup',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U9','U10','U11','U12','U13','U14','U15','U16','U17','U18','U19'],
    founded: 1990, firstSeason: 1990,
    stadium: 'Cromwell Soccer Complex',
    stadiumAddress: 'Cromwell, CT 06416',
    capacity: 500,
    primary: '#CC0000', secondary: '#FFFFFF',
    colorName: 'Red & White',
    abbr: 'CTR',
    coach: 'Director of Coaching',
    website: 'ctrush.com',
    instagram: '@connecticutrush', twitter: '@CTRush',
    description: 'Connecticut Rush is one of the largest and most established youth soccer organizations in Connecticut, offering elite competitive programs for players U9 through U19. The club competes in CJSA, ECRL, and USYS National Championships.',
    about: 'Founded in 1990, Connecticut Rush has developed hundreds of college-bound players and professionals. The club operates multiple boys and girls teams at every age level and is widely recognized as one of CT\'s premier development pathways.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: true },
  },
  {
    id: 'farmington-valley-sc',
    name: 'Farmington Valley SC',
    city: 'Farmington', state: 'CT',
    league: 'CJSA / CT State Cup',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 1978, firstSeason: 1978,
    stadium: 'Farmington Soccer Complex',
    stadiumAddress: 'Farmington, CT 06032',
    capacity: 400,
    primary: '#1A4E8A', secondary: '#FFFFFF',
    colorName: 'Royal Blue & White',
    abbr: 'FVS',
    coach: 'Director of Coaching',
    website: 'fvsc.net',
    instagram: '@farmingtonvalleysc', twitter: '',
    description: 'Farmington Valley Soccer Club is one of Connecticut\'s oldest and most respected youth organizations, serving communities in the Farmington Valley region including Farmington, Avon, Canton, Burlington, and Simsbury.',
    about: 'FVSC has been developing players since 1978, emphasizing long-term player development, team character, and a love of the game. The club fields competitive teams for both boys and girls at all age levels from U9 through U18.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'ct-fc-youth',
    name: 'Connecticut FC',
    city: 'Bloomfield', state: 'CT',
    league: 'ECRL / CJSA',
    leagueShort: 'ECRL',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U13','U14','U15','U16','U17','U18','U19'],
    founded: 2009, firstSeason: 2009,
    stadium: 'Covenant Prep School Fields',
    stadiumAddress: 'Bloomfield, CT 06002',
    capacity: 350,
    primary: '#003366', secondary: '#C9A227',
    colorName: 'Navy & Gold',
    abbr: 'CFC',
    coach: 'Director of Coaching',
    website: 'ctfc.net',
    instagram: '@connecticutfc', twitter: '@CTFC_Soccer',
    description: 'Connecticut FC is a competitive youth club offering ECRL and CJSA programs for players U13 through U19. The club is known for its college placement record and technical coaching staff.',
    about: 'CFC was founded to provide a high-level competitive environment for dedicated young players in the greater Hartford area. The club maintains strong relationships with college coaches and runs player identification programs across the state.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'eastern-ct-eagles',
    name: 'Eastern CT Eagles',
    city: 'Willimantic', state: 'CT',
    league: 'CJSA / CT State Cup',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 2001, firstSeason: 2001,
    stadium: 'Willimantic Youth Sports Complex',
    stadiumAddress: 'Willimantic, CT 06226',
    capacity: 300,
    primary: '#1F4E79', secondary: '#E2B04A',
    colorName: 'Navy & Gold',
    abbr: 'ECE',
    coach: 'Director of Coaching',
    website: 'easternctsc.com',
    instagram: '@easternctsc', twitter: '',
    description: 'Eastern CT Eagles serves the youth soccer community across eastern Connecticut, offering competitive travel programs for boys and girls U10 through U18 in the CJSA and state competitions.',
    about: 'One of the primary youth soccer organizations in eastern Connecticut, the Eagles draw players from Windham County and surrounding towns. The club focuses on developing technically sound players who compete at the regional and state level.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'west-hartford-sc',
    name: 'West Hartford SC',
    city: 'West Hartford', state: 'CT',
    league: 'CJSA',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U6','U7','U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 1969, firstSeason: 1969,
    stadium: 'Norfeldt / Charter Oak Park',
    stadiumAddress: 'West Hartford, CT 06107',
    capacity: 400,
    primary: '#005B8E', secondary: '#FFFFFF',
    colorName: 'Blue & White',
    abbr: 'WHY',
    coach: 'Director of Coaching',
    website: 'whsoccer.org',
    instagram: '@westhartsoccer', twitter: '',
    description: 'West Hartford Soccer Club is one of Connecticut\'s longest-running youth soccer organizations, serving West Hartford families since 1969 with recreational and competitive programs from U6 through U18.',
    about: 'WHSC is a community cornerstone offering both recreational leagues and competitive travel teams. The club\'s mission is to make the game accessible at all levels while providing pathways for those who wish to compete at higher levels.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'ridgefield-sc',
    name: 'Ridgefield Soccer Club',
    city: 'Ridgefield', state: 'CT',
    league: 'CJSA / Classic League',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 1974, firstSeason: 1974,
    stadium: 'Ridgefield Recreation Park',
    stadiumAddress: '195 Prospect Ridge Rd, Ridgefield, CT 06877',
    capacity: 350,
    primary: '#6B2737', secondary: '#C9A227',
    colorName: 'Maroon & Gold',
    abbr: 'RSC',
    coach: 'Director of Coaching',
    website: 'ridgefieldsc.org',
    instagram: '@ridgefieldsc', twitter: '',
    description: 'Ridgefield Soccer Club has been serving the Ridgefield youth community since 1974 with programs spanning recreational to competitive travel soccer for boys and girls.',
    about: 'RSC is one of Fairfield County\'s most established youth clubs, producing numerous college-level players over five decades. The club prides itself on community values, sportsmanship, and technical development.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'branford-sc',
    name: 'Branford Soccer Club',
    city: 'Branford', state: 'CT',
    league: 'CJSA',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 1972, firstSeason: 1972,
    stadium: 'Murphy Complex',
    stadiumAddress: 'Murphy Complex, Branford, CT 06405',
    capacity: 300,
    primary: '#004B23', secondary: '#FFFFFF',
    colorName: 'Green & White',
    abbr: 'BRN',
    coach: 'Director of Coaching',
    website: 'branfordsc.com',
    instagram: '@branfordsc', twitter: '',
    description: 'Branford Soccer Club is a community youth soccer organization on the Connecticut shoreline, offering recreational and competitive programs to Branford youth since 1972.',
    about: 'Branford SC serves the southern shoreline with both in-town recreational leagues and competitive travel teams, providing a pathway for players of all skill levels from beginners to high-level competitors.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'southington-sc',
    name: 'Southington Soccer Club',
    city: 'Southington', state: 'CT',
    league: 'CJSA / Classic League',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 1971, firstSeason: 1971,
    stadium: 'Southington Recreation Complex',
    stadiumAddress: 'Southington, CT 06489',
    capacity: 400,
    primary: '#2D6A4F', secondary: '#FFFFFF',
    colorName: 'Forest Green & White',
    abbr: 'SSC',
    coach: 'Director of Coaching',
    website: 'southingtonsoccer.org',
    instagram: '', twitter: '',
    description: 'Southington Soccer Club has been a staple of central Connecticut youth soccer since 1971, offering recreational and competitive programs for all ages.',
    about: 'SSC operates one of the most comprehensive youth programs in the greater Hartford suburbs, with both in-town leagues and travel teams competing in the CJSA and Classic League across Connecticut.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'oakwood-sc',
    name: 'Oakwood Soccer Club',
    city: 'Enfield', state: 'CT',
    league: 'CJSA',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U8','U9','U10','U11','U12','U13','U14','U15','U16','U17'],
    founded: 1985, firstSeason: 1985,
    stadium: 'Enfield Community Sports Complex',
    stadiumAddress: 'Enfield, CT 06082',
    capacity: 350,
    primary: '#5C4033', secondary: '#FFFFFF',
    colorName: 'Brown & White',
    abbr: 'OAK',
    coach: 'Director of Coaching',
    website: 'oakwoodsc.com',
    instagram: '@oakwoodscct', twitter: '',
    description: 'Oakwood Soccer Club is a northern Connecticut youth organization based in Enfield, offering competitive CJSA programs for players U8 through U17.',
    about: 'Serving communities in the Springfield/Hartford corridor including Enfield, Suffield, and East Windsor, Oakwood SC provides a local high-quality soccer environment for youth players seeking competitive opportunities without needing to travel to larger urban centers.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'shoreline-sc',
    name: 'Shoreline Soccer Club',
    city: 'Madison', state: 'CT',
    league: 'CJSA / Classic League',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 1988, firstSeason: 1988,
    stadium: 'Madison Sports Complex',
    stadiumAddress: 'Madison, CT 06443',
    capacity: 350,
    primary: '#005F73', secondary: '#FFFFFF',
    colorName: 'Teal & White',
    abbr: 'SSL',
    coach: 'Director of Coaching',
    website: 'shorelinesc.com',
    instagram: '@shorelinesc', twitter: '',
    description: 'Shoreline Soccer Club serves the Connecticut shoreline communities of Madison, Guilford, North Branford, and Clinton with competitive youth soccer programs from U9 through U18.',
    about: 'Founded in 1988 to serve shoreline communities, SSC has grown into one of the premier youth clubs along the Connecticut coast. The club emphasizes quality coaching, player development, and fostering a lifelong love of the game.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
];

// ── CT Competitive / EDP Youth Clubs (real contact info from club websites) ──
const CT_EDP_CLUBS = [
  {
    id: 'beachside-sc',
    name: 'Beachside Soccer Club',
    city: 'Norwalk', state: 'CT',
    league: 'MLS NEXT / EDP',
    leagueShort: 'MLS NEXT',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U13','U14','U15','U16','U17','U18','U19'],
    founded: 2003, firstSeason: 2003,
    stadium: 'Gallagher Field / Strawberry Hill',
    stadiumAddress: '10 Prospect St Unit 4, Norwalk, CT 06850',
    capacity: 400,
    primary: '#002868', secondary: '#FFFFFF',
    colorName: 'Navy & White',
    abbr: 'BSC',
    coach: 'Mickey Kydes',
    contactEmail: 'greg@beachside.soccer',
    contactPhone: '(203) 852-6969',
    contactUrl: 'https://beachsidesoccer.org',
    tryoutsUrl: 'https://beachsidesoccer.org/tryouts-2/',
    tryoutsNote: 'Open talent ID tryouts held seasonally for all competitive age groups. Check website for current session dates.',
    tournaments: ['MLS NEXT National Competitions','Capelli Sport International Tour (Denmark)'],
    website: 'beachsidesoccer.org',
    description: 'Beachside Soccer Club is one of Connecticut\'s most elite youth organizations, competing at the MLS NEXT level — the highest developmental league in U.S. youth soccer. The club has produced players who have gone on to college and professional careers.',
    about: 'Founded in Norwalk under Coaching Director Mickey Kydes, Beachside emphasizes high-level training, discipline, and commitment to excellence. The club runs Juniors developmental programs and competitive squads from U13 through U19 for both boys and girls.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'ginga-fc',
    name: 'Ginga FC',
    city: 'Woodbridge', state: 'CT',
    league: 'MLS NEXT / EDP / GA Aspire',
    leagueShort: 'MLS NEXT',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U7','U8','U9','U10','U11','U12','U13','U14','U15','U16','U17'],
    founded: 2010, firstSeason: 2010,
    stadium: 'Everson Soccer Complex',
    stadiumAddress: '21 South Bradley Rd, Woodbridge, CT 06525',
    capacity: 500,
    primary: '#228B22', secondary: '#FFD700',
    colorName: 'Forest Green & Gold',
    abbr: 'GNG',
    coach: 'Director of Coaching',
    contactEmail: 'GingaFC.CT@gmail.com',
    contactPhone: '(203) 298-4763',
    contactUrl: 'https://gingafc.com',
    tryoutsUrl: 'https://gingafc.com',
    tryoutsNote: 'Supplemental tryouts and ID clinics available year-round. Contact club for current openings by age group. Free ID clinics offered periodically.',
    tournaments: ['MLS NEXT League Play','GA Aspire Championships','EDP Spring/Fall Tournaments'],
    website: 'gingafc.com',
    description: 'Ginga FC operates across four Connecticut locations (Woodbridge, Hamden, Madison, Southbury) competing in MLS NEXT (boys), GA Aspire (girls), and EDP. The club is known for its Brazilian-inspired style and technical development approach.',
    about: 'With branches spanning from Woodbridge to the shoreline and Southbury, Ginga FC has grown into one of CT\'s most geographically accessible elite clubs. Boys teams compete in MLS NEXT and National League; girls in GA Aspire, DPL, and EDP.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'sporting-ct',
    name: 'Sporting CT',
    city: 'Middletown', state: 'CT',
    league: 'EDP / N1 / WPSL',
    leagueShort: 'EDP',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U12','U13','U14','U15','U16','U17','U19'],
    founded: 2008, firstSeason: 2008,
    stadium: 'Sporting CT Complex (CCR)',
    stadiumAddress: '395 Country Club Rd, Middletown, CT 06457',
    capacity: 600,
    primary: '#0C2340', secondary: '#C8A84B',
    colorName: 'Navy & Gold',
    abbr: 'SCT',
    coach: 'Goran Vasic',
    contactEmail: 'Goran@sportingct.com',
    contactPhone: '',
    contactUrl: 'https://sportingct.com/contact-us/',
    tryoutsUrl: 'https://sportingct.leagueapps.com/leagues/soccer/4471989-sporting-ct-tryouts-2025-2026-season',
    tryoutsNote: '2026/27 supplemental tryouts open via LeagueApps. Boys and girls programs from U12–U19. Also fields U-23 Men and WPSL Women.',
    tournaments: ['Sporting CT Spring Shootout (April)','Memorial Showcase (Memorial Day Weekend)','Gia\'s Memorial Classic'],
    website: 'sportingct.com',
    description: 'Sporting CT is a comprehensive youth and adult soccer organization based at their own complex in Middletown. The club competes in EDP, N1 League, NECSL, WPSL (women), and NAL, offering elite pathways from U12 through adult.',
    about: 'Under Executive Director Goran Vasic, Sporting CT focuses on the holistic development of players. The club hosts several of Connecticut\'s top tournaments and has grown to include a U-23 men\'s program and WPSL women\'s team.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'fsa-fc',
    name: 'FSA FC',
    city: 'Farmington', state: 'CT',
    league: 'ECNL / ECRL',
    leagueShort: 'ECNL',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U9','U10','U11','U12','U13','U14','U15','U16','U17','U18','U19'],
    founded: 2009, firstSeason: 2009,
    stadium: 'Farmington Sports Arena',
    stadiumAddress: '11 Executive Dr Suite 202, Farmington, CT 06032',
    capacity: 800,
    primary: '#00539C', secondary: '#FFB81C',
    colorName: 'Royal Blue & Gold',
    abbr: 'FSA',
    coach: 'Director of Coaching',
    contactEmail: 'clubadmin@fsafcunited.com',
    contactPhone: '(860) 404-5789',
    contactUrl: 'https://fsafc.com/contact-us/',
    tryoutsUrl: 'https://fsafc.com/tryouts/',
    tryoutsNote: 'Annual tryouts for all ECNL and ECRL age groups. Pre-ECNL ID Clinics held in spring. Check website for current schedule.',
    tournaments: ['FSA Columbus Cup (Oct, U9–U15)','Northeast Spring College Showcase (Mar, U15–U19)','ECNL Playoffs'],
    website: 'fsafc.com',
    description: 'FSA FC (Farmington Sports Arena Football Club) competes in the Elite Clubs National League (ECNL) — one of the highest-level youth soccer leagues in the country. Based at a 130,000 sq ft indoor facility with 9 outdoor fields, FSA FC serves U9 through U19.',
    about: 'Founded in 2009, FSA FC rapidly rose to become one of Connecticut\'s premier youth clubs. The club hosts the FSA Columbus Cup each fall and the Northeast Spring College Showcase, which draws college coaches from across the country.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'vale-sc',
    name: 'Vale Sports Club',
    city: 'Middletown', state: 'CT',
    league: 'EDP / MLS GO',
    leagueShort: 'EDP',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U4','U5','U6','U7','U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 2012, firstSeason: 2012,
    stadium: 'The Forge / Vale Fieldhouse',
    stadiumAddress: '49 Randolph Rd, Middletown, CT 06457',
    capacity: 600,
    primary: '#6A0DAD', secondary: '#FFFFFF',
    colorName: 'Purple & White',
    abbr: 'VSC',
    coach: 'Director of Coaching',
    contactEmail: 'contact@valesc.com',
    contactPhone: '(475) 331-5243',
    contactUrl: 'https://valesc.com',
    tryoutsUrl: 'https://valesc.com/easttryouts/',
    tryoutsNote: 'Each Vale location (Middletown, East, West, North/Windsor) holds separate tryouts. Check valesc.com for location-specific schedules.',
    tournaments: ['Vale Fieldhouse Indoor Tournaments','MLS GO League Competitions'],
    website: 'valesc.com',
    description: 'Vale Sports Club operates at multiple Connecticut locations (Middletown, East, West, and North/Windsor) offering programs from grassroots ages 3+ through competitive U18. The club plays in EDP and the MLS GO in-house league system.',
    about: 'Vale SC features two major facilities — The Forge (49 Randolph Rd) and the Vale Fieldhouse (1280 Newfield St) in Middletown — and runs competitive boys and girls programs alongside youth development, PASS skill training, and adult leagues.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'ole-fc',
    name: 'Ole FC',
    city: 'Monroe', state: 'CT',
    league: 'EDP / CFC-Ole',
    leagueShort: 'EDP',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U3','U4','U5','U6','U7','U8','U9','U10','U11','U12','U13','U14'],
    founded: 2004, firstSeason: 2004,
    stadium: 'Ole Training Center (OTC)',
    stadiumAddress: 'Monroe, CT 06468',
    capacity: 300,
    primary: '#D4202C', secondary: '#FFD700',
    colorName: 'Red & Gold',
    abbr: 'OLE',
    coach: 'Rodrigo Nunes',
    contactEmail: 'sam.olesoccer@gmail.com',
    contactPhone: '(203) 873-0309',
    contactUrl: 'https://olesoccerct.com/contact-us/',
    tryoutsUrl: 'https://olesoccerct.com/girlstryout/',
    tryoutsNote: 'Tryouts and supplemental placement available for girls and boys. The club also partners with CFC for travel and premier opportunities (2026/27 CFC tryouts available).',
    tournaments: ['Ole Summer Clinics','CFC-Ole League Play'],
    website: 'olesoccerct.com',
    description: 'Ole FC, founded in Monroe in 2004 by Rodrigo Nunes, offers developmental programs from age 18 months through U14. The club runs the Ole Developmental Academy (ODA) and partners with Connecticut FC for higher-level travel opportunities.',
    about: 'Known for its welcoming community culture and wide range of age-appropriate programs, Ole FC operates the Ole Training Center in Monroe and serves families across southwestern Connecticut with Stars programs, goalkeeping clinics, and adult leagues.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'ct-rush-select',
    name: 'CT Rush (Northeast Rush)',
    city: 'Southbury', state: 'CT',
    league: 'MLS NEXT / EDP',
    leagueShort: 'MLS NEXT',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U3','U4','U5','U6','U7','U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18','U19'],
    founded: 1997, firstSeason: 1997,
    stadium: 'Northeast Rush Regional Facility',
    stadiumAddress: 'Southbury, CT 06488',
    capacity: 500,
    primary: '#CC0000', secondary: '#FFFFFF',
    colorName: 'Red & White',
    abbr: 'NER',
    coach: 'Director of Coaching',
    contactEmail: 'info@northeastrush.com',
    contactPhone: '',
    contactUrl: 'https://northeastrush.com',
    tryoutsUrl: 'https://northeastrush.com/tryouts-2025',
    tryoutsNote: 'CT Rush operates five regional CT programs: CT Central, Northeast, South, Southeast, and South Central. CT Select teams compete in MLS NEXT. Check northeastrush.com/join-the-rush for team placement.',
    tournaments: ['MLS NEXT Competitions','Rush Cup','USYS Regional Championships'],
    website: 'northeastrush.com/connecticut',
    description: 'CT Rush (part of Northeast Rush) is one of the largest youth soccer organizations in New England, with five regional CT programs and an elite CT Select program that competes in MLS NEXT. The club serves players from age 3 through high school.',
    about: 'Northeast Rush CT operates CT Central, CT Northeast, CT South, CT Southeast, and CT South Central programs, plus an advanced CT Select pathway that joined MLS NEXT for the 2025-2026 season. The club emphasizes age-appropriate coaching and long-term player development.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: true },
  },
  {
    id: 'inter-ct-fc',
    name: 'Inter Connecticut FC',
    city: 'Easton', state: 'CT',
    league: 'EDP / USL',
    leagueShort: 'EDP',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U6','U7','U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18','U19'],
    founded: 2005, firstSeason: 2005,
    stadium: 'Easton-Redding Field Complex',
    stadiumAddress: 'Easton, CT 06612',
    capacity: 400,
    primary: '#003DA5', secondary: '#000000',
    colorName: 'Royal Blue & Black',
    abbr: 'ICT',
    coach: 'Stephen Bell',
    contactEmail: 'info@interctfc.com',
    contactPhone: '',
    contactUrl: 'https://www.interctfc.com',
    tryoutsUrl: 'https://www.interctfc.com/tryouts',
    tryoutsNote: 'Annual tryouts held for all travel age groups. Micro Soccer program for youngest players. Litchfield Hills branch also holds separate sessions. Contact stephen@interctfc.com or info@interctfc.com.',
    tournaments: ['EDP Spring/Fall Tournaments','Inter CT Invitational'],
    website: 'interctfc.com',
    description: 'Inter Connecticut FC is a major EDP club serving Fairfield and Litchfield County with pathways from Micro Soccer (U6) through U19 and beyond. The club offers academy, travel, and premier programs and has a separate Litchfield Hills branch.',
    about: 'Inter CT FC provides a complete soccer pathway for Connecticut players. Director of Coaching Stephen Bell oversees competitive programs, while the Litchfield Hills branch (directed by Dave Shannon) serves the northwest corner of the state.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'cfc',
    name: 'Connecticut Football Club',
    city: 'Bethany', state: 'CT',
    league: 'ECNL / ECRL / N1',
    leagueShort: 'ECNL',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U3','U4','U5','U6','U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18','U19'],
    founded: 2000, firstSeason: 2000,
    stadium: 'CFC Park',
    stadiumAddress: 'Bethany, CT 06524',
    capacity: 600,
    primary: '#00205B', secondary: '#C8102E',
    colorName: 'Navy & Red',
    abbr: 'CFC',
    coach: 'Director of Coaching',
    contactEmail: 'info@connecticutfootballclub.com',
    contactPhone: '',
    contactUrl: 'https://connecticutfootballclub.org',
    tryoutsUrl: 'https://connecticutfootballclub.org',
    tryoutsNote: 'CFC fields statewide teams in ECNL, ECRL, and N1 League. Use the "Find My CFC Team" form on the website to be matched with the right program for your location and age group.',
    tournaments: ['ECNL National Event','ECRL Regional Playoffs','CFC Summer Summit'],
    website: 'connecticutfootballclub.org',
    description: 'Connecticut Football Club (CFC) is a statewide ECNL club offering one of Connecticut\'s highest-level youth pathways for both boys and girls. Programs include Little Kickers (U3–U6), CFC Bethany Academy, and full ECNL/ECRL competitive programs.',
    about: 'CFC maintains CFC Park in Bethany as its primary facility and fields teams across CT through regional programs including CFC North, CFC South, CFC Valley, and CFC Ole. The club competes in ECNL — one of the top youth leagues in the US.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: true, youtube: false },
  },
  {
    id: 'trumbull-united-sc',
    name: 'Trumbull United SC',
    city: 'Trumbull', state: 'CT',
    league: 'EDP / CJSA',
    leagueShort: 'EDP',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 2005, firstSeason: 2005,
    stadium: 'InSports Centers',
    stadiumAddress: '29 Trefoil Dr, Trumbull, CT 06611',
    capacity: 350,
    primary: '#D40000', secondary: '#FFFFFF',
    colorName: 'Red & White',
    abbr: 'TUS',
    coach: 'Director of Coaching',
    contactEmail: 'trumbullunitedsoccerclub@gmail.com',
    contactPhone: '',
    contactUrl: 'https://www.trumbullunited.com',
    tryoutsUrl: 'https://www.trumbullunited.com',
    tryoutsNote: 'Annual tryouts (May) for Grades 2–8 and High School. Both sessions required. Location: InSports Centers, 29 Trefoil Drive, Trumbull. Check website for exact dates.',
    tournaments: ['EDP Spring/Fall Tournaments','CJSA State Cup'],
    website: 'trumbullunited.com',
    description: 'Trumbull United SC offers Academy, Travel, and Premier soccer programs for players in Grades 2–8 and High School in Trumbull and surrounding Fairfield County communities.',
    about: 'Based at InSports Centers in Trumbull, the club provides a structured developmental path from recreational through premier competition. Travel serves as a stepping stone to the Premier program, which competes at the highest EDP and state levels.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'fairfield-united-sa',
    name: 'Fairfield United SA',
    city: 'Fairfield', state: 'CT',
    league: 'CJSA/SWD',
    leagueShort: 'CJSA',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U8','U9','U10','U11','U12','U13','U14','U15'],
    founded: 1985, firstSeason: 1985,
    stadium: 'Fairfield Recreation Fields',
    stadiumAddress: 'Fairfield, CT 06824',
    capacity: 300,
    primary: '#B22222', secondary: '#FFFFFF',
    colorName: 'Crimson & White',
    abbr: 'FUS',
    coach: 'Director of Coaching',
    contactEmail: 'fusaboard@gmail.com',
    contactPhone: '',
    contactUrl: 'https://www.fairfieldunited.com',
    tryoutsUrl: 'https://www.fairfieldunited.com/programs/tryouts',
    tryoutsNote: 'Competitive travel soccer for Fairfield residents in grades U8–U14/U15. Tryout schedules posted on website and communicated via email/PlayMetrics.',
    tournaments: ['CJSA State Cup','SWD District Championships'],
    website: 'fairfieldunited.com',
    description: 'Fairfield United Soccer Association provides competitive travel soccer exclusively for Fairfield residents, competing in the CJSA Southwestern District. The club focuses on player development within a town-specific community program.',
    about: 'One of Fairfield County\'s long-standing youth organizations, FUSA ensures Fairfield residents have access to quality competitive soccer without leaving their town program. The club develops players from U8 through high school levels.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'revolution-united-fc',
    name: 'Revolution United FC',
    city: 'Naugatuck', state: 'CT',
    league: 'EDP / CJSA',
    leagueShort: 'EDP',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 2008, firstSeason: 2008,
    stadium: 'Naugatuck Recreation Complex',
    stadiumAddress: 'Naugatuck, CT 06770',
    capacity: 300,
    primary: '#002395', secondary: '#ED2939',
    colorName: 'Blue & Red',
    abbr: 'RUF',
    coach: 'Director of Coaching',
    contactEmail: '',
    contactPhone: '',
    contactUrl: 'https://www.revolutionunitedfc.com',
    tryoutsUrl: 'https://www.revolutionunitedfc.com',
    tryoutsNote: 'Tryouts held for all EDP and CJSA competitive teams. Visit revolutionunitedfc.com for current schedule.',
    tournaments: ['EDP Connecticut Championships','CJSA State Cup'],
    website: 'revolutionunitedfc.com',
    description: 'Revolution United FC serves the Naugatuck Valley with competitive EDP and CJSA soccer programs for boys and girls from U8 through U18.',
    about: 'RUFC provides high-quality competitive soccer in the Naugatuck Valley, drawing players from Naugatuck, Beacon Falls, Seymour, Derby, and surrounding communities. The club competes in EDP and the CJSA State Cup.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'yankee-united-fc',
    name: 'Yankee United FC',
    city: 'Enfield', state: 'CT',
    league: 'EDP / CJSA',
    leagueShort: 'EDP',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 1999, firstSeason: 1999,
    stadium: 'Yankee Soccer Complex',
    stadiumAddress: 'Enfield, CT 06082',
    capacity: 400,
    primary: '#003087', secondary: '#C8102E',
    colorName: 'Navy & Red',
    abbr: 'YUF',
    coach: 'Director of Coaching',
    contactEmail: '',
    contactPhone: '',
    contactUrl: 'http://www.yankeeunited.com',
    tryoutsUrl: 'http://www.yankeeunited.com',
    tryoutsNote: 'EDP and CJSA competitive teams for boys and girls. Visit yankeeunited.com for tryout information.',
    tournaments: ['EDP Championships','CJSA State Cup','Yankee United Invitational'],
    website: 'yankeeunited.com',
    description: 'Yankee United FC is a long-established EDP club in north-central Connecticut, serving the greater Enfield and Springfield corridor with boys and girls competitive programs from U8 through U18.',
    about: 'One of CT\'s more established EDP clubs, Yankee United draws players from Enfield, Windsor Locks, Suffield, East Windsor, and the Springfield border area. The club competes in EDP and CJSA state competitions.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'northeast-united-sc',
    name: 'Northeast United SC',
    city: 'Tolland', state: 'CT',
    league: 'EDP / CJSA',
    leagueShort: 'EDP',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U8','U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 2003, firstSeason: 2003,
    stadium: 'Tolland Recreation Complex',
    stadiumAddress: 'Tolland, CT 06084',
    capacity: 300,
    primary: '#006400', secondary: '#FFD700',
    colorName: 'Green & Gold',
    abbr: 'NUS',
    coach: 'Director of Coaching',
    contactEmail: '',
    contactPhone: '',
    contactUrl: 'https://www.northeastunited.org',
    tryoutsUrl: 'https://www.northeastunited.org',
    tryoutsNote: 'EDP competitive teams for boys and girls. Serving Tolland, Coventry, Vernon, and eastern CT communities. Visit northeastunited.org for tryout schedule.',
    tournaments: ['EDP Tournaments','CJSA State Cup'],
    website: 'northeastunited.org',
    description: 'Northeast United SC serves eastern Connecticut communities including Tolland, Coventry, and Vernon with EDP and CJSA competitive soccer programs.',
    about: 'NUSC provides competitive youth soccer for the northeastern CT region, offering boys and girls programs from U8 through U18 in EDP and CJSA competition.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'shoreline-united-sc',
    name: 'Shoreline United SC',
    city: 'East Haddam', state: 'CT',
    league: 'EDP / CJSA',
    leagueShort: 'EDP',
    tier: 'Youth',
    tierLevel: 5,
    type: 'youth',
    ageGroups: ['U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 2006, firstSeason: 2006,
    stadium: 'Haddam-Killingworth Fields',
    stadiumAddress: 'East Haddam, CT 06423',
    capacity: 300,
    primary: '#0077C2', secondary: '#FFFFFF',
    colorName: 'Blue & White',
    abbr: 'SUS',
    coach: 'Director of Coaching',
    contactEmail: '',
    contactPhone: '',
    contactUrl: 'https://www.shorelineunitedsoccerclub.com',
    tryoutsUrl: 'https://www.shorelineunitedsoccerclub.com',
    tryoutsNote: 'EDP and CJSA teams for the Connecticut River and shoreline region. Serving communities including East Haddam, Haddam, Killingworth, Chester, and Deep River.',
    tournaments: ['EDP Connecticut Tournaments','CJSA State Cup'],
    website: 'shorelineunitedsoccerclub.com',
    description: 'Shoreline United SC serves the lower Connecticut River valley and shoreline with competitive EDP and CJSA soccer for boys and girls.',
    about: 'Shoreline United draws players from the lower Connecticut River corridor — East Haddam, Haddam, Chester, Deep River, Killingworth, and surrounding communities — providing a local competitive option for shoreline families.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
];


// ─── Additional community youth clubs ────────────────────────────────────────
const CT_YOUTH_EXTRA = [
  {
    id: 'cheshire-sc',
    name: 'Cheshire Soccer Club',
    city: 'Cheshire', state: 'CT',
    league: 'CJSA', leagueShort: 'CJSA',
    tier: 'Youth', tierLevel: 5,
    type: 'youth',
    ageGroups: ['U6','U7','U8','U9','U10','U11','U12','U13','U14','U15','U16'],
    founded: 1975, firstSeason: 1975,
    stadium: 'Cheshire Community Fields',
    stadiumAddress: 'Cheshire, CT 06410',
    capacity: 300,
    primary: '#003087', secondary: '#FFFFFF',
    colorName: 'Blue & White',
    abbr: 'CSC',
    coach: 'Club Director',
    contactUrl: 'https://www.cheshiresoccerclub.org/',
    tryoutsNote: 'Open registration for recreational and travel teams. Contact the club for travel team tryout dates.',
    tournaments: ['CJSA State Cup','Central CT Invitational'],
    website: 'cheshiresoccerclub.org',
    description: 'One of the oldest and most established youth soccer clubs in Connecticut, serving Cheshire since 1975.',
    about: 'Cheshire Soccer Club has developed generations of Connecticut soccer players across recreational and travel programs. The club offers age-appropriate competition for every skill level.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'darien-sa',
    name: 'Darien Soccer Association',
    city: 'Darien', state: 'CT',
    league: 'CJSA / SWD', leagueShort: 'CJSA',
    tier: 'Youth', tierLevel: 5,
    type: 'youth',
    ageGroups: ['U6','U7','U8','U9','U10','U11','U12','U13','U14'],
    founded: 1968, firstSeason: 1968,
    stadium: 'Darien Recreation Complex',
    stadiumAddress: 'Darien, CT 06820',
    capacity: 400,
    primary: '#002868', secondary: '#BF0A30',
    colorName: 'Navy & Red',
    abbr: 'DSA',
    coach: 'Various Travel Coaches',
    contactUrl: 'http://www.dariensoccer.org/',
    tryoutsNote: 'Travel team evaluations held each spring and fall. Recreational registration open year-round.',
    tournaments: ['CJSA State Cup','Fairfield County Invitationals'],
    website: 'dariensoccer.org',
    description: "One of the most established soccer organizations in Fairfield County, serving Darien's youth since 1968.",
    about: 'Darien Soccer Association runs recreational and travel programs for players from pre-K through high school, with competitive travel teams in the CJSA South West District.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'manchester-sc',
    name: 'Manchester Soccer Club',
    city: 'Manchester', state: 'CT',
    league: 'CJSA', leagueShort: 'CJSA',
    tier: 'Youth', tierLevel: 5,
    type: 'youth',
    ageGroups: ['U6','U7','U8','U9','U10','U11','U12','U13','U14','U15','U16','U17'],
    founded: 1970, firstSeason: 1970,
    stadium: 'Manchester Recreation Fields',
    stadiumAddress: 'Manchester, CT 06040',
    capacity: 350,
    primary: '#8B0000', secondary: '#FFFFFF',
    colorName: 'Red & White',
    abbr: 'MSC',
    coach: 'Club Director',
    contactUrl: 'http://www.manchestersoccerclub.com/',
    tryoutsNote: 'Travel team tryouts held in the spring. Recreational programs open to all skill levels.',
    tournaments: ['CJSA State Cup','Hartford County League'],
    website: 'manchestersoccerclub.com',
    description: 'Manchester Soccer Club has served the Manchester and east Hartford County community for over 50 years.',
    about: 'MSC runs recreational and travel programs across all age groups, competing in CJSA leagues throughout the state. The club emphasizes player development and community involvement.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'glastonbury-hartwell',
    name: 'Glastonbury Hartwell Soccer Club',
    city: 'Glastonbury', state: 'CT',
    league: 'CJSA', leagueShort: 'CJSA',
    tier: 'Youth', tierLevel: 5,
    type: 'youth',
    ageGroups: ['U8','U9','U10','U11','U12','U13','U14','U15','U16'],
    founded: 1982, firstSeason: 1982,
    stadium: 'Glastonbury Recreation Fields',
    stadiumAddress: 'Glastonbury, CT 06033',
    capacity: 300,
    primary: '#006400', secondary: '#FFFFFF',
    colorName: 'Green & White',
    abbr: 'GHS',
    coach: 'Club Director',
    contactUrl: 'http://www.glastonburysoccer.org/',
    tryoutsNote: 'Recreational and travel programs available. Travel tryouts held each spring for the following fall season.',
    tournaments: ['CJSA State Cup','Hartford County Tournaments'],
    website: 'glastonburysoccer.org',
    description: 'Glastonbury Hartwell Soccer Club provides recreational and competitive soccer in one of Connecticut\'s premier soccer communities.',
    about: 'Serving Glastonbury families since 1982, GHSC has grown into one of the strongest youth soccer organizations in the greater Hartford area, producing many high school and collegiate players.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'east-lyme-sa',
    name: 'East Lyme Soccer Association',
    city: 'East Lyme', state: 'CT',
    league: 'CJSA / ECSYL', leagueShort: 'CJSA',
    tier: 'Youth', tierLevel: 5,
    type: 'youth',
    ageGroups: ['U6','U7','U8','U9','U10','U11','U12','U13','U14','U15'],
    founded: 1978, firstSeason: 1978,
    stadium: 'Flanders Fields',
    stadiumAddress: 'East Lyme, CT 06333',
    capacity: 250,
    primary: '#003366', secondary: '#C8A951',
    colorName: 'Navy & Gold',
    abbr: 'ELSA',
    coach: 'Club Director',
    contactUrl: 'https://www.eastlymesoccer.org/',
    tryoutsNote: 'Travel team evaluations each spring. Recreational registration open all year.',
    tournaments: ['CJSA State Cup','Eastern CT Youth Soccer League'],
    website: 'eastlymesoccer.org',
    description: 'East Lyme Soccer Association has served the southeastern Connecticut shoreline community for nearly five decades.',
    about: 'ELSA runs programs from U6 through U15, offering both recreational and travel competition in the Eastern Connecticut Youth Soccer League and CJSA.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'hamden-sa',
    name: 'Hamden Soccer Association',
    city: 'Hamden', state: 'CT',
    league: 'CJSA', leagueShort: 'CJSA',
    tier: 'Youth', tierLevel: 5,
    type: 'youth',
    ageGroups: ['U6','U7','U8','U9','U10','U11','U12','U13','U14'],
    founded: 1970, firstSeason: 1970,
    stadium: 'Hamden Recreation Fields',
    stadiumAddress: 'Hamden, CT 06514',
    capacity: 300,
    primary: '#1a237e', secondary: '#FFFFFF',
    colorName: 'Blue & White',
    abbr: 'HSA',
    coach: 'Club Director',
    contactUrl: 'http://www.hamdensoccer.com/',
    tryoutsNote: 'Travel team tryouts each spring. Recreational open enrollment for all ages.',
    tournaments: ['CJSA State Cup','New Haven County League'],
    website: 'hamdensoccer.com',
    description: 'Hamden Soccer Association serves the greater New Haven County area with recreational and travel soccer programs.',
    about: "One of New Haven County's pillars of youth soccer, Hamden SA develops players from beginner recreational level through competitive travel in the CJSA.",
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
];

// ─── Additional competitive / EDP clubs ──────────────────────────────────────
const CT_EDP_EXTRA = [
  {
    id: 'chelsea-piers-sc',
    name: 'Chelsea Piers FC',
    city: 'Stamford', state: 'CT',
    league: 'ECRL / CJSA', leagueShort: 'ECRL',
    tier: 'Youth', tierLevel: 5,
    type: 'youth',
    ageGroups: ['U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 2012, firstSeason: 2012,
    stadium: 'Chelsea Piers Connecticut',
    stadiumAddress: '1 Blachley Rd, Stamford, CT 06902',
    capacity: 500,
    primary: '#00205B', secondary: '#009BDE',
    colorName: 'Navy & Sky Blue',
    abbr: 'CPFC',
    coach: 'Chelsea Piers Academy Staff',
    contactEmail: 'soccer@chelseapiersct.com',
    contactPhone: '(203) 989-1000',
    contactUrl: 'https://www.chelseapiersct.com/soccer/club-program/',
    tryoutsUrl: 'https://www.chelseapiersct.com/soccer/club-program/',
    tryoutsNote: 'Annual club tryouts held in late spring. Chelsea Piers FC operates within the Chelsea Piers Connecticut sports complex in Stamford.',
    tournaments: ['ECRL Showcase Events','CJSA State Cup','EDP Connecticut'],
    website: 'chelseapiersct.com',
    description: 'Chelsea Piers FC is the competitive youth soccer program within the acclaimed Chelsea Piers Connecticut sports complex in Stamford.',
    about: 'Operating out of one of the premier sports facilities in the Northeast, Chelsea Piers FC provides elite youth training and ECRL competition for Fairfield County players.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'gzs-united',
    name: 'GZS United',
    city: 'New London', state: 'CT',
    league: 'EDP / CJSA', leagueShort: 'EDP',
    tier: 'Youth', tierLevel: 5,
    type: 'youth',
    ageGroups: ['U9','U10','U11','U12','U13','U14','U15','U16','U17'],
    founded: 2008, firstSeason: 2008,
    stadium: 'Bates Woods Park',
    stadiumAddress: 'New London, CT 06320',
    capacity: 300,
    primary: '#006400', secondary: '#FFDE00',
    colorName: 'Green & Yellow',
    abbr: 'GZS',
    coach: 'Club Director',
    contactUrl: 'https://www.generationzsoccer.com/gzs-united-premier',
    tryoutsUrl: 'https://www.generationzsoccer.com/gzs-united-premier',
    tryoutsNote: 'Premier teams hold annual evaluations. Contact the club for current tryout schedule.',
    tournaments: ['EDP Connecticut','CJSA State Cup','Eastern CT Invitational'],
    website: 'generationzsoccer.com',
    description: "GZS United is southeastern Connecticut's premier competitive youth soccer club, competing in the EDP league.",
    about: "Generation Z Soccer's competitive arm, GZS United Premier serves the New London county area with high-level youth competition in the EDP and CJSA State leagues.",
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
  {
    id: 'ct-impact-united',
    name: 'CT Impact United Soccer Academy',
    city: 'Hartford', state: 'CT',
    league: 'EDP / CJSA', leagueShort: 'EDP',
    tier: 'Youth', tierLevel: 5,
    type: 'youth',
    ageGroups: ['U9','U10','U11','U12','U13','U14','U15','U16','U17','U18'],
    founded: 2010, firstSeason: 2010,
    stadium: 'Colt Park',
    stadiumAddress: 'Hartford, CT 06114',
    capacity: 400,
    primary: '#003087', secondary: '#E5001C',
    colorName: 'Blue & Red',
    abbr: 'CTIU',
    coach: 'Academy Director',
    contactUrl: 'https://www.impactusact.com/',
    tryoutsUrl: 'https://www.impactusact.com/',
    tryoutsNote: 'Annual tryouts held in spring for fall season teams. The academy emphasizes player development and college pathways.',
    tournaments: ['EDP Connecticut','CJSA State Cup','Hartford Invitational'],
    website: 'impactusact.com',
    description: 'CT Impact United Soccer Academy develops Hartford-area players through elite coaching and competitive EDP play.',
    about: 'Based in Hartford, CT Impact United bridges the gap between recreational and elite youth soccer for players from the Greater Hartford area, offering structured development pathways.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'ja-elite',
    name: 'JA Elite Soccer',
    city: 'Stamford', state: 'CT',
    league: 'EDP / ECRL', leagueShort: 'EDP',
    tier: 'Youth', tierLevel: 5,
    type: 'youth',
    ageGroups: ['U9','U10','U11','U12','U13','U14','U15','U16','U17','U18','U19'],
    founded: 2005, firstSeason: 2005,
    stadium: 'Fairfield County Fields',
    stadiumAddress: 'Stamford, CT 06902',
    capacity: 300,
    primary: '#1B1B1B', secondary: '#E31837',
    colorName: 'Black & Red',
    abbr: 'JAE',
    coach: 'Julian Agosto',
    contactUrl: 'https://www.jaelitesoccer.com/',
    tryoutsUrl: 'https://www.jaelitesoccer.com/',
    tryoutsNote: 'Team evaluations held annually. Contact via website for specific age group dates.',
    tournaments: ['EDP Connecticut','ECRL Showcases','CJSA State Cup'],
    website: 'jaelitesoccer.com',
    description: 'JA Elite is a Stamford-based competitive club offering elite development for youth players across Fairfield County.',
    about: 'Founded by veteran coach Julian Agosto, JA Elite has grown into one of Fairfield County\'s most respected competitive clubs, competing at the EDP and ECRL levels.',
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: true, twitter: false, youtube: false },
  },
  {
    id: 'liberty-fc-norwich',
    name: 'Liberty Football Club',
    city: 'Norwich', state: 'CT',
    league: 'EDP / CJSA', leagueShort: 'EDP',
    tier: 'Youth', tierLevel: 5,
    type: 'youth',
    ageGroups: ['U9','U10','U11','U12','U13','U14','U15','U16','U17'],
    founded: 2003, firstSeason: 2003,
    stadium: 'Mohegan Park Fields',
    stadiumAddress: 'Norwich, CT 06360',
    capacity: 350,
    primary: '#CC0000', secondary: '#FFFFFF',
    colorName: 'Red & White',
    abbr: 'LFC',
    coach: 'Club Director',
    contactUrl: 'http://www.libertyfootball.org/',
    tryoutsUrl: 'http://www.libertyfootball.org/',
    tryoutsNote: 'Annual evaluations in spring. Serving the greater Norwich and New London county area.',
    tournaments: ['EDP Connecticut','CJSA State Cup','Eastern CT Tournaments'],
    website: 'libertyfootball.org',
    description: 'Liberty Football Club is the premier competitive youth soccer club for eastern Connecticut, based in Norwich.',
    about: "Serving the eastern Connecticut region since 2003, Liberty FC provides competitive EDP and CJSA soccer for boys and girls from Norwich, New London county, and surrounding communities.",
    wins: 0, draws: 0, losses: 0, gf: 0, ga: 0,
    roster: [], recentResults: [], upcoming: [],
    socialLinks: { facebook: true, instagram: false, twitter: false, youtube: false },
  },
];

// Combined array for pages that need all clubs
const ALL_CLUBS = [...CT_CLUBS, ...CT_YOUTH_CLUBS, ...CT_YOUTH_EXTRA, ...CT_EDP_CLUBS, ...CT_EDP_EXTRA];

function getClubById(id) {
  return ALL_CLUBS.find(c => c.id === id) || null;
}

function clubPts(c) { return c.wins * 3 + c.draws; }
function clubGD(c)  { return c.gf - c.ga; }
// Win % = wins / games played. Returns null when no games are on record yet (nothing to divide).
function clubWinPct(c) {
  const played = c.wins + c.draws + c.losses;
  if (!played) return null;
  return Math.round((c.wins / played) * 1000) / 10;
}

function tierBadgeHtml(tier) {
  if (tier === 'Professional')        return '<span style="background:rgba(245,168,0,.14);color:#F5A800;border:1px solid rgba(245,168,0,.3);font-size:.62rem;font-weight:700;letter-spacing:.07em;text-transform:uppercase;padding:3px 9px;border-radius:6px;">Pro</span>';
  if (tier === 'Semi-Professional')   return '<span style="background:rgba(43,124,233,.14);color:#5BA3FF;border:1px solid rgba(43,124,233,.28);font-size:.62rem;font-weight:700;letter-spacing:.07em;text-transform:uppercase;padding:3px 9px;border-radius:6px;">Semi-Pro</span>';
  if (tier === 'Youth')               return '<span style="background:rgba(92,221,139,.12);color:#5CDD8B;border:1px solid rgba(92,221,139,.25);font-size:.62rem;font-weight:700;letter-spacing:.07em;text-transform:uppercase;padding:3px 9px;border-radius:6px;">Youth</span>';
  return '<span style="background:rgba(255,255,255,.08);color:rgba(255,255,255,.55);border:1px solid rgba(255,255,255,.12);font-size:.62rem;font-weight:700;letter-spacing:.07em;text-transform:uppercase;padding:3px 9px;border-radius:6px;">Amateur</span>';
}
