// Real, verified season storylines for CT's professional/semi-pro clubs (see
// each club page for live data). Shared between news.html (renders the feed)
// and dashboard.html (site search).
const NEWS_STORIES = [
  {
    id: "week-2026-08-20",
    category: "recap",
    badge: "Weekly Recap", badgeClass: "badge-recap",
    date: "Aug 20, 2026",
    clubId: null,
    title: "This Week in CT Soccer — August 20, 2026",
    summary: "Results and what's next for Hartford Athletic, CT United FC, New Haven United FC, AC Connecticut, and CT Rush.",
    commentary: "",
    body: [
      "<p style=\"font-size:.95rem;line-height:1.8;color:rgba(255,255,255,.75);margin:0 0 20px;\">Results and what's next for Hartford Athletic, CT United FC, New Haven United FC, AC Connecticut, and CT Rush.</p>",
      "<h2 style=\"font-size:1.05rem;font-weight:800;color:#fff;margin:0 0 14px;\">Club by Club</h2>",
      "\n      <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px 20px;margin-bottom:14px;\">\n        <div style=\"font-size:.95rem;font-weight:800;color:#fff;margin-bottom:6px;\">Hartford Athletic</div>\n        <p style=\"font-size:.88rem;line-height:1.7;color:rgba(255,255,255,.65);margin:0;\">Hartford Athletic beat Miami FC 2-1 at home (Aug 15, 2026) — now 9th of 13 in USL Championship.</p>\n        <p style=\"font-size:.82rem;color:rgba(255,255,255,.4);margin:6px 0 0;\">Next up: vs Birmingham Legion FC, Aug 29, 2026 (7:00 PM).</p>\n      </div>\n\n      <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px 20px;margin-bottom:14px;\">\n        <div style=\"font-size:.95rem;font-weight:800;color:#fff;margin-bottom:6px;\">CT United FC</div>\n        <p style=\"font-size:.88rem;line-height:1.7;color:rgba(255,255,255,.65);margin:0;\">As of Aug 9, 2026, the most recent result on file for CT United FC is a loss (1-2) at home vs New England Revolution II — now 7th of 16 in MLS Next Pro.</p>\n        <p style=\"font-size:.82rem;color:rgba(255,255,255,.4);margin:6px 0 0;\">Next up: @ Philadelphia Union II, Aug 23, 2026 (7:00 PM).</p>\n      </div>\n\n      <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px 20px;margin-bottom:14px;\">\n        <div style=\"font-size:.95rem;font-weight:800;color:#fff;margin-bottom:6px;\">New Haven United FC</div>\n        <p style=\"font-size:.88rem;line-height:1.7;color:rgba(255,255,255,.65);margin:0;\">As of Jul 25, 2026, the most recent result on file for New Haven United FC is a loss (0-2) on the road vs Bristol Rhythm AFC — now 1st of 6 in NPSL (National Premier Soccer League).</p>\n        \n      </div>\n\n      <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px 20px;margin-bottom:14px;\">\n        <div style=\"font-size:.95rem;font-weight:800;color:#fff;margin-bottom:6px;\">AC Connecticut</div>\n        <p style=\"font-size:.88rem;line-height:1.7;color:rgba(255,255,255,.65);margin:0;\">AC Connecticut's USL League Two season concluded on Jul 7, 2026 — final match lost 0-2 at home vs Western Mass Pioneers. No matches currently scheduled.</p>\n        \n      </div>\n\n      <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px 20px;margin-bottom:14px;\">\n        <div style=\"font-size:.95rem;font-weight:800;color:#fff;margin-bottom:6px;\">CT Rush (USL2)</div>\n        <p style=\"font-size:.88rem;line-height:1.7;color:rgba(255,255,255,.65);margin:0;\">CT Rush (USL2)'s USL League Two season concluded on Jul 1, 2026 — final match lost 0-2 at home vs AC Connecticut. No matches currently scheduled.</p>\n        \n      </div>",
    ],
  },
  {
    id: "ctu-debut",
    category: "milestone",
    badge: "Milestone", badgeClass: "badge-milestone",
    date: "Mar 1, 2026",
    clubId: "ct-united-fc",
    title: "CT United FC opens inaugural season with a 3–1 road win over FC Cincinnati 2",
    summary: "Connecticut's first-ever MLS Next Pro club made history in its debut match, the first step in a season that has since seen the club climb to a winning record.",
  },
  {
    id: "nhu-conference",
    category: "milestone",
    badge: "Milestone", badgeClass: "badge-milestone",
    date: "Jul 19, 2026",
    clubId: "new-haven-united-fc",
    title: "New Haven United FC wins the NPSL North Atlantic Conference outright",
    summary: "In just its second season, New Haven United finished 1st in the North Atlantic Conference before advancing to the NPSL National Semifinal — the deepest playoff run by a Connecticut NPSL club.",
  },
  {
    id: "hfd-usl2",
    category: "result",
    badge: "Match Result", badgeClass: "badge-result",
    date: "Aug 9, 2026",
    clubId: "hartford-athletic",
    title: "Hartford Athletic draw 1–1 with Indy Eleven",
    summary: "Jordan Scarlett's second-half equalizer salvaged a point on the road, part of a stretch that has seen Hartford draw four of its last six USL Championship matches.",
  },
  {
    id: "ctu-streak",
    category: "result",
    badge: "Match Result", badgeClass: "badge-result",
    date: "Aug 1, 2026",
    clubId: "ct-united-fc",
    title: "CT United FC beats Orlando City B 4–2, fourth win in five matches",
    summary: "A four-goal outing continued CT United's strong summer stretch in MLS Next Pro, pushing the club's win percentage well above .500 for the season.",
  },
  {
    id: "usl2-season-wrap",
    category: "milestone",
    badge: "Season Wrap", badgeClass: "badge-milestone",
    date: "Jul 12, 2026",
    clubId: "ac-connecticut",
    title: "USL League Two regular season wraps up for AC Connecticut and CT Rush",
    summary: "Both Connecticut clubs closed out the Northeast Division regular season — CT Rush finished 8th, AC Connecticut 9th. CT Rush's debut USL2 season is now complete.",
  },
  {
    id: "site-live-data",
    category: "site",
    badge: "Platform Update", badgeClass: "badge-site",
    date: "Aug 13, 2026",
    clubId: null,
    title: "Live results now tracking for Hartford Athletic, AC Connecticut, and CT Rush",
    summary: "CT Soccer now pulls real results and upcoming fixtures automatically for all three USL-affiliated clubs, refreshing every five minutes.",
  },
  {
    id: "site-coaching-launch",
    category: "site",
    badge: "Platform Update", badgeClass: "badge-site",
    date: "Aug 14, 2026",
    clubId: null,
    title: "New: Coaching Clinics directory with real CJSA/US Soccer course pricing",
    summary: "Browse every Grassroots-through-B-License course CJSA and US Soccer offer in Connecticut, filterable by tier and ranked by value.",
  },
];
