// Real, verified season storylines for CT's professional/semi-pro clubs (see
// each club page for live data). Shared between news.html (renders the feed)
// and dashboard.html (site search).
const NEWS_STORIES = [
  {
    id: 'ctu-debut',
    category: 'milestone',
    badge: 'Milestone', badgeClass: 'badge-milestone',
    date: 'Mar 1, 2026',
    clubId: 'ct-united-fc',
    title: 'CT United FC opens inaugural season with a 3–1 road win over FC Cincinnati 2',
    summary: 'Connecticut\'s first-ever MLS Next Pro club made history in its debut match, the first step in a season that has since seen the club climb to a winning record.',
  },
  {
    id: 'nhu-conference',
    category: 'milestone',
    badge: 'Milestone', badgeClass: 'badge-milestone',
    date: 'Jul 19, 2026',
    clubId: 'new-haven-united-fc',
    title: 'New Haven United FC wins the NPSL North Atlantic Conference outright',
    summary: 'In just its second season, New Haven United finished 1st in the North Atlantic Conference before advancing to the NPSL National Semifinal — the deepest playoff run by a Connecticut NPSL club.',
  },
  {
    id: 'hfd-usl2',
    category: 'result',
    badge: 'Match Result', badgeClass: 'badge-result',
    date: 'Aug 9, 2026',
    clubId: 'hartford-athletic',
    title: 'Hartford Athletic draw 1–1 with Indy Eleven',
    summary: 'Jordan Scarlett\'s second-half equalizer salvaged a point on the road, part of a stretch that has seen Hartford draw four of its last six USL Championship matches.',
  },
  {
    id: 'ctu-streak',
    category: 'result',
    badge: 'Match Result', badgeClass: 'badge-result',
    date: 'Aug 1, 2026',
    clubId: 'ct-united-fc',
    title: 'CT United FC beats Orlando City B 4–2, fourth win in five matches',
    summary: 'A four-goal outing continued CT United\'s strong summer stretch in MLS Next Pro, pushing the club\'s win percentage well above .500 for the season.',
  },
  {
    id: 'usl2-season-wrap',
    category: 'milestone',
    badge: 'Season Wrap', badgeClass: 'badge-milestone',
    date: 'Jul 12, 2026',
    clubId: 'ac-connecticut',
    title: 'USL League Two regular season wraps up for AC Connecticut and CT Rush',
    summary: 'Both Connecticut clubs closed out the Northeast Division regular season — CT Rush finished 8th, AC Connecticut 9th. CT Rush\'s debut USL2 season is now complete.',
  },
  {
    id: 'site-live-data',
    category: 'site',
    badge: 'Platform Update', badgeClass: 'badge-site',
    date: 'Aug 13, 2026',
    clubId: null,
    title: 'Live results now tracking for Hartford Athletic, AC Connecticut, and CT Rush',
    summary: 'CT Soccer now pulls real results and upcoming fixtures automatically for all three USL-affiliated clubs, refreshing every five minutes.',
  },
  {
    id: 'site-coaching-launch',
    category: 'site',
    badge: 'Platform Update', badgeClass: 'badge-site',
    date: 'Aug 14, 2026',
    clubId: null,
    title: 'New: Coaching Clinics directory with real CJSA/US Soccer course pricing',
    summary: 'Browse every Grassroots-through-B-License course CJSA and US Soccer offer in Connecticut, filterable by tier and ranked by value.',
  },
];
