// Real, verified season storylines for CT's professional/semi-pro clubs (see
// each club page for live data). Shared between news.html (renders the feed)
// and dashboard.html (site search).
const NEWS_STORIES = [
  {
    id: "spotlight-vale-sc",
    category: "spotlight",
    badge: "Club Spotlight", badgeClass: "badge-spotlight",
    date: "Aug 20, 2026",
    clubId: "vale-sc",
    title: "Club Spotlight: Vale Rush United",
    summary: "A closer look at Vale Rush United — history, leadership, and what makes the club stand out.",
    body: [
      "<p style=\"font-size:.95rem;line-height:1.8;color:rgba(255,255,255,.75);margin:0 0 20px;\">Vale Rush United is the elite competitive tier formed in March 2026 when Vale Sports Club's Newell's division merged with CT Rush Select (Northeast Rush's MLS NEXT pathway), competing in the MLS Next Academy Division and National Academy League (boys) and the ECNL Regional League and National Academy League (girls). The broader Vale Sports Club organization continues to run grassroots and development programs across Middletown, East, and West.</p>",
      "<h2 style=\"font-size:1.05rem;font-weight:800;color:#fff;margin:0 0 14px;\">History &amp; Leadership</h2>",
      "<p style=\"font-size:.9rem;line-height:1.75;color:rgba(255,255,255,.65);margin:0 0 8px;\">Vale Rush United is led day-to-day by Lloyd Warren (contact for all Vale Rush United inquiries), with Greg Cumpstone as Boys Technical Director and Tom Newell as Girls Technical Director — both lead coaching across Vale's elite programs and previously led CT Select before the merger. Above them sit Vale Sports Club's founder Zach Eddinger (Owner) and Adriano Allain (Executive Director), who oversee the whole organization. Outside the elite Vale Rush United tier, Vale Sports Club still runs separate grassroots/development divisions with their own Directors of Coaching: Billy Kissane (Middletown), Jeremy Wilson (East), and Dalton Lemoine (West); North/Windsor hosts Vale's PASS skills program. Note: Northeast Rush's other Connecticut regional programs (CT Central, CT South, CT East, CT South Central) were not part of this merger and remain a separate organization based in Southbury.</p>",
      "<p style=\"font-size:.85rem;color:rgba(255,255,255,.45);margin:0;\">Head of program: Lloyd Warren (Vale Rush United contact) — see description for full leadership</p>",
      "<h2 style=\"font-size:1.05rem;font-weight:800;color:#fff;margin:24px 0 14px;\">By the Numbers</h2>",
      "<div style=\"display:grid;grid-template-columns:repeat(3,1fr);gap:12px;\">\n        <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px;text-align:center;\">\n          <div style=\"font-size:1.3rem;font-weight:800;color:#fff;margin-bottom:4px;\">14 yrs</div>\n          <div style=\"font-size:.7rem;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:rgba(255,255,255,.4);\">Running Since 2012</div>\n        </div>\n        <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px;text-align:center;\">\n          <div style=\"font-size:1.3rem;font-weight:800;color:#fff;margin-bottom:4px;\">U3–U19</div>\n          <div style=\"font-size:.7rem;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:rgba(255,255,255,.4);\">Age Groups</div>\n        </div>\n        <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px;text-align:center;\">\n          <div style=\"font-size:1.3rem;font-weight:800;color:#fff;margin-bottom:4px;\">Middletown &amp; Southbury</div>\n          <div style=\"font-size:.7rem;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:rgba(255,255,255,.4);\">Home Base</div>\n        </div></div>",
      "\n      <h2 style=\"font-size:1.05rem;font-weight:800;color:#fff;margin:24px 0 14px;\">How to Get Involved</h2>\n      <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px 20px;\">\n        <p style=\"font-size:.88rem;line-height:1.7;color:rgba(255,255,255,.65);margin:0 0 10px;\">Vale Rush United (elite tier) holds unified 2026/27 tryouts — see link above. Vale's grassroots/development divisions in Middletown, East, and West continue to hold separate, location-specific tryouts.</p>\n        <a href=\"https://valesc.leagueapps.com/events/4889960-vale-rush-united-202627-season---tryouts\" target=\"_blank\" rel=\"noopener\" style=\"font-size:.88rem;color:var(--accent-lt);text-decoration:none;display:block;margin-bottom:6px;\">Tryout info &rarr;</a>\n        <p style=\"font-size:.85rem;color:rgba(255,255,255,.5);margin:0;\">Contact: contact@valesc.com</p>\n      </div>",
    ],
  },
  {
    id: "spotlight-ginga-fc",
    category: "spotlight",
    badge: "Club Spotlight", badgeClass: "badge-spotlight",
    date: "Aug 20, 2026",
    clubId: "ginga-fc",
    title: "Club Spotlight: Ginga FC",
    summary: "A closer look at Ginga FC — history, leadership, and what makes the club stand out.",
    body: [
      "<p style=\"font-size:.95rem;line-height:1.8;color:rgba(255,255,255,.75);margin:0 0 20px;\">Ginga FC operates a Woodbridge home base plus a Hamden branch (via Hamden United) and a Madison-based Girls Coastal program, competing in MLS NEXT (boys), GA Aspire (girls), and EDP. The club is known for its Brazilian-inspired style and technical development approach.</p>",
      "<h2 style=\"font-size:1.05rem;font-weight:800;color:#fff;margin:0 0 14px;\">History &amp; Leadership</h2>",
      "<p style=\"font-size:.9rem;line-height:1.75;color:rgba(255,255,255,.65);margin:0 0 8px;\">Led by Director of Coaching Rodrigo Silva, a Pro License coach and former professional player, Ginga FC runs its main academy out of Woodbridge alongside a Hamden branch operated through Hamden United and a Madison-based Girls Coastal program; it also partners with Southbury FC to help manage teams there. Boys teams compete in MLS NEXT and National League; girls in GA Aspire, DPL, and EDP.</p>",
      "<p style=\"font-size:.85rem;color:rgba(255,255,255,.45);margin:0;\">Head of program: Rodrigo Silva (Director of Coaching)</p>",
      "<h2 style=\"font-size:1.05rem;font-weight:800;color:#fff;margin:24px 0 14px;\">By the Numbers</h2>",
      "<div style=\"display:grid;grid-template-columns:repeat(3,1fr);gap:12px;\">\n        <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px;text-align:center;\">\n          <div style=\"font-size:1.3rem;font-weight:800;color:#fff;margin-bottom:4px;\">16 yrs</div>\n          <div style=\"font-size:.7rem;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:rgba(255,255,255,.4);\">Running Since 2010</div>\n        </div>\n        <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px;text-align:center;\">\n          <div style=\"font-size:1.3rem;font-weight:800;color:#fff;margin-bottom:4px;\">U7–U17</div>\n          <div style=\"font-size:.7rem;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:rgba(255,255,255,.4);\">Age Groups</div>\n        </div>\n        <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px;text-align:center;\">\n          <div style=\"font-size:1.3rem;font-weight:800;color:#fff;margin-bottom:4px;\">Woodbridge, Hamden &amp; Madison</div>\n          <div style=\"font-size:.7rem;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:rgba(255,255,255,.4);\">Home Base</div>\n        </div></div>",
      "\n      <h2 style=\"font-size:1.05rem;font-weight:800;color:#fff;margin:24px 0 14px;\">How to Get Involved</h2>\n      <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px 20px;\">\n        <p style=\"font-size:.88rem;line-height:1.7;color:rgba(255,255,255,.65);margin:0 0 10px;\">Supplemental tryouts and ID clinics available year-round. Contact club for current openings by age group. Free ID clinics offered periodically.</p>\n        <a href=\"https://gingafc.com\" target=\"_blank\" rel=\"noopener\" style=\"font-size:.88rem;color:var(--accent-lt);text-decoration:none;display:block;margin-bottom:6px;\">Tryout info &rarr;</a>\n        <p style=\"font-size:.85rem;color:rgba(255,255,255,.5);margin:0;\">Contact: GingaFC.CT@gmail.com</p>\n      </div>",
    ],
  },
  {
    id: "spotlight-ct-united-fc",
    category: "spotlight",
    badge: "Club Spotlight", badgeClass: "badge-spotlight",
    date: "Aug 20, 2026",
    clubId: "ct-united-fc",
    title: "Club Spotlight: CT United FC",
    summary: "A closer look at CT United FC — history, leadership, and what makes the club stand out.",
    body: [
      "<p style=\"font-size:.95rem;line-height:1.8;color:rgba(255,255,255,.75);margin:0 0 20px;\">CT United FC is Connecticut's first MLS Next Pro club, the third tier of the American soccer pyramid and MLS's official player-development league. Founded in 2024 and based in Bridgeport, the club is owned by Connecticut Sports Group and made its debut in March 2026.</p>",
      "<h2 style=\"font-size:1.05rem;font-weight:800;color:#fff;margin:0 0 14px;\">History &amp; Leadership</h2>",
      "<p style=\"font-size:.9rem;line-height:1.75;color:rgba(255,255,255,.65);margin:0 0 8px;\">CT United FC is building toward a permanent waterfront stadium on a former dog-racing track site in Bridgeport, playing its inaugural home matches at UConn's Morrone Stadium and Yale's Reese Stadium in the meantime. Head coach Shavar Thomas, a former Jamaican national team captain, leads the club's first-team roster and its MLS Next academy program.</p>",
      "<p style=\"font-size:.85rem;color:rgba(255,255,255,.45);margin:0;\">Head of program: Shavar Thomas</p>",
      "<h2 style=\"font-size:1.05rem;font-weight:800;color:#fff;margin:24px 0 14px;\">By the Numbers</h2>",
      "<div style=\"display:grid;grid-template-columns:repeat(3,1fr);gap:12px;\">\n        <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px;text-align:center;\">\n          <div style=\"font-size:1.3rem;font-weight:800;color:#fff;margin-bottom:4px;\">10-2-9</div>\n          <div style=\"font-size:.7rem;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:rgba(255,255,255,.4);\">Record (W-D-L)</div>\n        </div>\n        <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px;text-align:center;\">\n          <div style=\"font-size:1.3rem;font-weight:800;color:#fff;margin-bottom:4px;\">7th of 16</div>\n          <div style=\"font-size:.7rem;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:rgba(255,255,255,.4);\">MLS Next Pro</div>\n        </div>\n        <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px;text-align:center;\">\n          <div style=\"font-size:1.3rem;font-weight:800;color:#fff;margin-bottom:4px;\">+3</div>\n          <div style=\"font-size:.7rem;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:rgba(255,255,255,.4);\">Goal Differential</div>\n        </div></div>",
      "\n      <h2 style=\"font-size:1.05rem;font-weight:800;color:#fff;margin:24px 0 14px;\">How to Follow</h2>\n      <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px 20px;\">\n        <a href=\"https://ctunited.com\" target=\"_blank\" rel=\"noopener\" style=\"font-size:.88rem;color:var(--accent-lt);text-decoration:none;display:block;margin-bottom:6px;\">Official site &rarr;</a>\n        <p style=\"font-size:.85rem;color:rgba(255,255,255,.5);margin:0;\">Full schedule, roster, and live results below.</p>\n      </div>",
    ],
  },
  {
    id: "spotlight-new-haven-united-fc",
    category: "spotlight",
    badge: "Club Spotlight", badgeClass: "badge-spotlight",
    date: "Aug 20, 2026",
    clubId: "new-haven-united-fc",
    title: "Club Spotlight: New Haven United FC",
    summary: "A closer look at New Haven United FC — history, leadership, and what makes the club stand out.",
    body: [
      "<p style=\"font-size:.95rem;line-height:1.8;color:rgba(255,255,255,.75);margin:0 0 20px;\">New Haven United FC is a semi-professional club in the NPSL's Northeast Region, North Atlantic Conference. Founded in 2025 as the spiritual successor to the Elm City Express, the club plays at Yale's Reese Stadium and features players from 14 different countries.</p>",
      "<h2 style=\"font-size:1.05rem;font-weight:800;color:#fff;margin:0 0 14px;\">History &amp; Leadership</h2>",
      "<p style=\"font-size:.9rem;line-height:1.75;color:rgba(255,255,255,.65);margin:0 0 8px;\">Led by president Jason Price and head coach Kledis Capollari — a former Hartford Athletic assistant and youth development lead — New Haven United reached the NPSL conference final in its debut 2025 season and won the North Atlantic Conference outright in 2026 before falling to eventual national runner-up Bristol Rhythm AFC in the club's first-ever National Semifinal appearance.</p>",
      "<p style=\"font-size:.85rem;color:rgba(255,255,255,.45);margin:0;\">Head of program: Kledis Capollari</p>",
      "<h2 style=\"font-size:1.05rem;font-weight:800;color:#fff;margin:24px 0 14px;\">By the Numbers</h2>",
      "<div style=\"display:grid;grid-template-columns:repeat(3,1fr);gap:12px;\">\n        <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px;text-align:center;\">\n          <div style=\"font-size:1.3rem;font-weight:800;color:#fff;margin-bottom:4px;\">6-2-2</div>\n          <div style=\"font-size:.7rem;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:rgba(255,255,255,.4);\">Record (W-D-L)</div>\n        </div>\n        <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px;text-align:center;\">\n          <div style=\"font-size:1.3rem;font-weight:800;color:#fff;margin-bottom:4px;\">1st of 6</div>\n          <div style=\"font-size:.7rem;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:rgba(255,255,255,.4);\">NPSL (National Premier Soccer League)</div>\n        </div>\n        <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px;text-align:center;\">\n          <div style=\"font-size:1.3rem;font-weight:800;color:#fff;margin-bottom:4px;\">+7</div>\n          <div style=\"font-size:.7rem;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:rgba(255,255,255,.4);\">Goal Differential</div>\n        </div></div>",
      "\n      <h2 style=\"font-size:1.05rem;font-weight:800;color:#fff;margin:24px 0 14px;\">How to Follow</h2>\n      <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px 20px;\">\n        <a href=\"https://newhavenunited.com\" target=\"_blank\" rel=\"noopener\" style=\"font-size:.88rem;color:var(--accent-lt);text-decoration:none;display:block;margin-bottom:6px;\">Official site &rarr;</a>\n        <p style=\"font-size:.85rem;color:rgba(255,255,255,.5);margin:0;\">Full schedule, roster, and live results below.</p>\n      </div>",
    ],
  },
  {
    id: "spotlight-hartford-athletic",
    category: "spotlight",
    badge: "Club Spotlight", badgeClass: "badge-spotlight",
    date: "Aug 20, 2026",
    clubId: "hartford-athletic",
    title: "Club Spotlight: Hartford Athletic",
    summary: "A closer look at Hartford Athletic — history, leadership, and what makes the club stand out.",
    body: [
      "<p style=\"font-size:.95rem;line-height:1.8;color:rgba(255,255,255,.75);margin:0 0 20px;\">Hartford Athletic is a professional soccer club competing in USL Championship, the second division of American soccer. Founded in 2018 with their first season in 2019, they are Connecticut's only professional soccer club and play at Trinity Health Stadium (formerly Dillon Stadium) in Hartford.</p>",
      "<h2 style=\"font-size:1.05rem;font-weight:800;color:#fff;margin:0 0 14px;\">History &amp; Leadership</h2>",
      "<p style=\"font-size:.9rem;line-height:1.75;color:rgba(255,255,255,.65);margin:0 0 8px;\">Hartford Athletic was founded as part of a grassroots effort to bring professional soccer back to Connecticut's capital. The club quickly built a passionate local fanbase and competes against top USL Championship clubs across the United States.</p>",
      "<p style=\"font-size:.85rem;color:rgba(255,255,255,.45);margin:0;\">Head of program: Harry Watling</p>",
      "<h2 style=\"font-size:1.05rem;font-weight:800;color:#fff;margin:24px 0 14px;\">By the Numbers</h2>",
      "<div style=\"display:grid;grid-template-columns:repeat(3,1fr);gap:12px;\">\n        <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px;text-align:center;\">\n          <div style=\"font-size:1.3rem;font-weight:800;color:#fff;margin-bottom:4px;\">5-9-5</div>\n          <div style=\"font-size:.7rem;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:rgba(255,255,255,.4);\">Record (W-D-L)</div>\n        </div>\n        <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px;text-align:center;\">\n          <div style=\"font-size:1.3rem;font-weight:800;color:#fff;margin-bottom:4px;\">9th of 13</div>\n          <div style=\"font-size:.7rem;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:rgba(255,255,255,.4);\">USL Championship</div>\n        </div>\n        <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px;text-align:center;\">\n          <div style=\"font-size:1.3rem;font-weight:800;color:#fff;margin-bottom:4px;\">-3</div>\n          <div style=\"font-size:.7rem;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:rgba(255,255,255,.4);\">Goal Differential</div>\n        </div></div>",
      "\n      <h2 style=\"font-size:1.05rem;font-weight:800;color:#fff;margin:24px 0 14px;\">How to Follow</h2>\n      <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px 20px;\">\n        <a href=\"https://hartfordathletic.com\" target=\"_blank\" rel=\"noopener\" style=\"font-size:.88rem;color:var(--accent-lt);text-decoration:none;display:block;margin-bottom:6px;\">Official site &rarr;</a>\n        <p style=\"font-size:.85rem;color:rgba(255,255,255,.5);margin:0;\">Full schedule, roster, and live results below.</p>\n      </div>",
    ],
  },
  {
    id: "week-2026-08-20",
    category: "recap",
    badge: "Weekly Recap", badgeClass: "badge-recap",
    date: "Aug 20, 2026",
    clubId: null,
    title: "This Week in CT Soccer — August 20, 2026",
    summary: "Results and what's next for Hartford Athletic, CT United FC, New Haven United FC, AC Connecticut, and CT Rush.",
    commentary: "",
    body: [
      "<p style=\"font-size:.95rem;line-height:1.8;color:rgba(255,255,255,.75);margin:0 0 20px;\">Results and what's next for Hartford Athletic, CT United FC, New Haven United FC, AC Connecticut, and CT Rush.</p>",
      "<h2 style=\"font-size:1.05rem;font-weight:800;color:#fff;margin:0 0 14px;\">Club by Club</h2>",
      "\n      <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px 20px;margin-bottom:14px;\">\n        <div style=\"font-size:.95rem;font-weight:800;color:#fff;margin-bottom:6px;\">Hartford Athletic</div>\n        <p style=\"font-size:.88rem;line-height:1.7;color:rgba(255,255,255,.65);margin:0;\">Hartford Athletic beat Miami FC 2-1 at home (Aug 15, 2026) — now 9th of 13 in USL Championship.</p>\n        <p style=\"font-size:.82rem;color:rgba(255,255,255,.4);margin:6px 0 0;\">Next up: vs Birmingham Legion FC, Aug 29, 2026 (7:00 PM).</p>\n      </div>\n\n      <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px 20px;margin-bottom:14px;\">\n        <div style=\"font-size:.95rem;font-weight:800;color:#fff;margin-bottom:6px;\">CT United FC</div>\n        <p style=\"font-size:.88rem;line-height:1.7;color:rgba(255,255,255,.65);margin:0;\">As of Aug 9, 2026, the most recent result on file for CT United FC is a loss (1-2) at home vs New England Revolution II — now 7th of 16 in MLS Next Pro.</p>\n        <p style=\"font-size:.82rem;color:rgba(255,255,255,.4);margin:6px 0 0;\">Next up: @ Philadelphia Union II, Aug 23, 2026 (7:00 PM).</p>\n      </div>\n\n      <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px 20px;margin-bottom:14px;\">\n        <div style=\"font-size:.95rem;font-weight:800;color:#fff;margin-bottom:6px;\">New Haven United FC</div>\n        <p style=\"font-size:.88rem;line-height:1.7;color:rgba(255,255,255,.65);margin:0;\">As of Jul 25, 2026, the most recent result on file for New Haven United FC is a loss (0-2) on the road vs Bristol Rhythm AFC — now 1st of 6 in NPSL (National Premier Soccer League).</p>\n        \n      </div>\n\n      <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px 20px;margin-bottom:14px;\">\n        <div style=\"font-size:.95rem;font-weight:800;color:#fff;margin-bottom:6px;\">AC Connecticut</div>\n        <p style=\"font-size:.88rem;line-height:1.7;color:rgba(255,255,255,.65);margin:0;\">AC Connecticut's USL League Two season concluded on Jul 7, 2026 — final match lost 0-2 at home vs Western Mass Pioneers. No matches currently scheduled.</p>\n        \n      </div>\n\n      <div style=\"background:var(--navy-800);border:1px solid var(--border);border-radius:14px;padding:18px 20px;margin-bottom:14px;\">\n        <div style=\"font-size:.95rem;font-weight:800;color:#fff;margin-bottom:6px;\">CT Rush (USL2)</div>\n        <p style=\"font-size:.88rem;line-height:1.7;color:rgba(255,255,255,.65);margin:0;\">CT Rush (USL2)'s USL League Two season concluded on Jul 1, 2026 — final match lost 0-2 at home vs AC Connecticut. No matches currently scheduled.</p>\n        \n      </div>",
    ],
  },
  {
    id: "ctu-debut",
    category: "milestone",
    badge: "Milestone", badgeClass: "badge-milestone",
    date: "Mar 1, 2026",
    clubId: "ct-united-fc",
    title: "CT United FC opens inaugural season with a 3–1 road win over FC Cincinnati 2",
    summary: "Connecticut's first-ever MLS Next Pro club made history in its debut match, the first step in a season that has since seen the club climb to a winning record.",
  },
  {
    id: "nhu-conference",
    category: "milestone",
    badge: "Milestone", badgeClass: "badge-milestone",
    date: "Jul 19, 2026",
    clubId: "new-haven-united-fc",
    title: "New Haven United FC wins the NPSL North Atlantic Conference outright",
    summary: "In just its second season, New Haven United finished 1st in the North Atlantic Conference before advancing to the NPSL National Semifinal — the deepest playoff run by a Connecticut NPSL club.",
  },
  {
    id: "hfd-usl2",
    category: "result",
    badge: "Match Result", badgeClass: "badge-result",
    date: "Aug 9, 2026",
    clubId: "hartford-athletic",
    title: "Hartford Athletic draw 1–1 with Indy Eleven",
    summary: "Jordan Scarlett's second-half equalizer salvaged a point on the road, part of a stretch that has seen Hartford draw four of its last six USL Championship matches.",
  },
  {
    id: "ctu-streak",
    category: "result",
    badge: "Match Result", badgeClass: "badge-result",
    date: "Aug 1, 2026",
    clubId: "ct-united-fc",
    title: "CT United FC beats Orlando City B 4–2, fourth win in five matches",
    summary: "A four-goal outing continued CT United's strong summer stretch in MLS Next Pro, pushing the club's win percentage well above .500 for the season.",
  },
  {
    id: "usl2-season-wrap",
    category: "milestone",
    badge: "Season Wrap", badgeClass: "badge-milestone",
    date: "Jul 12, 2026",
    clubId: "ac-connecticut",
    title: "USL League Two regular season wraps up for AC Connecticut and CT Rush",
    summary: "Both Connecticut clubs closed out the Northeast Division regular season — CT Rush finished 8th, AC Connecticut 9th. CT Rush's debut USL2 season is now complete.",
  },
  {
    id: "site-live-data",
    category: "site",
    badge: "Platform Update", badgeClass: "badge-site",
    date: "Aug 13, 2026",
    clubId: null,
    title: "Live results now tracking for Hartford Athletic, AC Connecticut, and CT Rush",
    summary: "CT Soccer now pulls real results and upcoming fixtures automatically for all three USL-affiliated clubs, refreshing every five minutes.",
  },
  {
    id: "site-coaching-launch",
    category: "site",
    badge: "Platform Update", badgeClass: "badge-site",
    date: "Aug 14, 2026",
    clubId: null,
    title: "New: Coaching Clinics directory with real CJSA/US Soccer course pricing",
    summary: "Browse every Grassroots-through-B-License course CJSA and US Soccer offer in Connecticut, filterable by tier and ranked by value.",
  },
];
