import puppeteer from 'puppeteer';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dir = path.join(__dirname, 'temporary screenshots');
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
let n = 1;
while (fs.existsSync(path.join(dir, `screenshot-${n}-search-test.png`))) n++;
const outPath = path.join(dir, `screenshot-${n}-search-test.png`);
const browser = await puppeteer.launch({ args: ['--no-sandbox','--disable-setuid-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900, deviceScaleFactor: 2 });
await page.goto('http://localhost:3000/dashboard.html', { waitUntil: 'networkidle2', timeout: 30000 });
await page.evaluate(() => showSection('clubs'));
await new Promise(r => setTimeout(r, 400));
await page.type('#club-search', 'Hartford');
await new Promise(r => setTimeout(r, 400));
await page.screenshot({ path: outPath });
await browser.close();
console.log('Saved:', outPath);
